---
title: ''
output:
  word_document:
    reference_docx: mytemplate.docx
  pdf_document: default
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, results = 'asis', fig.width = 4, fig.height = 3.5)
```

```{r load packages, results = 'hide', message = FALSE}

library(devtools)
##devtools::install_github("hadley/ggplot2", force = TRUE)
# install_github("hadley/ggplot2@v2.2.0")
# devtools::install_github("dkahle/ggmap")
#devtools::install_github("adletaw/captioner")
library(tidyr)
library(ggmap)
library(maps)
library(mapdata)
library(lubridate) 
library(sciplot)
#library(rgdal) #??
#library(data.table)
library(dplyr)
library(cowplot)
library(ggplot2)
library(stats)
library(captioner)
library(knitr)
library(reshape2)
library(stringr)
library(magrittr)
library(sciplot) #se()
library(scales)
library(stats) #kruskal.test
library(PMCMR) # posthoc.kruskal.nemenyi.test https://cran.r-project.org/web/packages/PMCMR/vignettes/PMCMR.pdf
library(strucchange) # chow test https://cran.r-project.org/web/packages/strucchange/strucchange.pdf  
library(pgirmess) #kruskalmc
#library(GGally)

case <- function(x)
  paste0(toupper(substr(x, 1, 1)), tolower(substring(x, 2)))

figs <- captioner(prefix = "Figure")
tbls <- captioner(prefix = "Table")

presfigure_theme <- function(...) {
  theme(text = element_text(family = 'Times'),
    #text = element_text(size = 11),
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, color = "black", size = 24),
    axis.text.y = element_text(vjust = 0.5, color = "black", size = 22), 
    axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 0), 
                              size = 26),
    axis.title.x = element_text(size = 26), 
    axis.line.y = element_line(colour = "black"), 
    axis.line.x = element_line(colour = "black"), 
    plot.background = element_rect(), 
    panel.background = element_blank(), 
    panel.grid = element_blank(), 
    legend.title = element_blank(),
    legend.key = element_blank(),
    legend.text = element_text(size = 34),
    ...)
}

color6 <- c("#e45f56", "#363e7e", "#4aaaa5", "#a3d39c", "#f6b61c", "#3b98ee", "#999aa7")
color3 <- c("#e45f56", "#363e7e", "#a3d39c")
color4_HI <- c("#3b98ee", "#a3d39c", "#e45f56", "#f6b61c")
color4_age <- c("#ff8000", "#363e7e", "#3b98ee", "#a3d39c")
color2 <- c("#e45f56", "#363e7e")
color_maps <- c("grey30", "#3b98ee", "#a3d39c", "#e45f56", "#f6b61c")
color_seas <- c("#a3d39c", "#e45f56", "#f6b61c", "#6ea3ec")


```

```{r load tables, echo = FALSE, results = 'hide'}
# setwd("./Figures")

# setwd("..") 
```

```{r load pre-cleaned csv, echo = FALSE}

setwd("~/Documents/Research/Cet_Strandings/")

cetaceans <- read.csv("cetacean_data_CleaningOuput00_18.csv", header = TRUE, na.strings = "", 
                      stringsAsFactors = FALSE) %>% 
  transform(Season = ifelse(Month.of.Observation %in% c('DEC', 'JAN', 'FEB'), 'Winter',
                        ifelse(Month.of.Observation %in% c('MAR', 'APR', 'MAY'), 'Spring',
                            ifelse(Month.of.Observation %in% c('JUN', 'JUL', 'AUG'), 'Summer', 'Fall')))) %>%
  transform(Season = factor(Season, levels = c("Spring", "Summer", "Fall", "Winter"))) %>%
  transform(sci_name = paste(Genus, Species, sep = " "))

#setwd("..") 

# cetaceans$Month.of.Observation <- factor(cetaceans$Month.of.Observation, levels = c('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'))

cetaceans$County <- factor(cetaceans$County, levels = c('Whatcom', 'San Juan', 'Island', 'Skagit', 'Snohomish', 'King', 'Kitsap', 'Pierce', 'Thurston', 'Mason', 'Clallam', 'Jefferson', 'Grays Harbor', 'Pacific', 'Cowlitz', 'Clark', 'Clatsop', 'Columbia', 'Multnomah', 'Tillamook', 'Lincoln', 'Lane', 'Douglas', 'Coos', 'Curry'))


```

```{r map basics}

#ani.options(convert = shQuote('c:/program files/imagemagick/magick.exe'))
#animation::ani.options(ani.width = 900, ani.height = 1000, loop = 5)

# allbox <- c(-129, 41, -117, 50)
# ORbox <- c(-125, 41.91, -121.5, 46.28)
# WAbox <- c(-125.2, 46, -121.7, 49.1)
# pugetbox <- c(-123.4, 46.96, -121.7, 48.86)

cetaceans_mapping <- cetaceans %>% 
  transform(Longitude = as.numeric(Longitude),
            Latitude = as.numeric(Latitude),
            long_corr = as.numeric(long_corr),
            lat_corr = as.numeric(lat_corr)) 
sum(is.na(cetaceans$long_corr))

# weight_sp <- cetaceans %>%
#   filter(Cetacean.Common.Name != 'Unidentified') %>%
#    group_by(Cetacean.Common.Name) %>%
#   dplyr::summarize(weight = n()/nrow(cetaceans))

cetaceans_mapping_sp <- cetaceans_mapping %>% filter(sci_name != 'NA NA') 
#%>%
  #merge(weight_sp, by = 'Cetacean.Common.Name')

test <- cetaceans_mapping_sp %>% group_by(sci_name) %>%
  summarize(cnt = n_distinct(National.Database.Number))

cetaceans_mapping_sp_small <- cetaceans_mapping_sp %>%
  merge(test, by = 'sci_name') %>%
  filter(cnt > 13 & sci_name != 'NA NA')

cetaceans_mapping_sp_smaller <- cetaceans_mapping_sp_small %>%
  filter(Cetacean.Common.Name %in% c('Harbor porpoise', 'Gray whale', 'Humpback whale', 'Striped dolphin', 'Dalls porpoise'))

# cetaceans_mapping_HI <- cetaceans_mapping %>% 
#   filter(Findings.of.Human.Interaction == 'Y')

#state outline
canada <- map_data("world", region = "Canada") %>%
  filter(lat > 41.6 & lat < 52) %>%
  filter(long > -131 & long < -112) 

pnw_state_outline <- map_data("state", region = c("oregon", "washington")) %>%
  bind_rows(canada) 

```

```{r static maps}

strands_species <- ggplot(pnw_state_outline) +
geom_polygon(aes(x = long, y = lat, group = group), fill = "grey93", color = "grey50", size = 0.2) + 
  coord_fixed(1, ylim = c(42.3, 49.15), xlim = c(-125, -121.8)) + 
  geom_point(data = cetaceans_mapping_sp_small,
             aes(x = long_corr, y = lat_corr), col = 'grey40', size = 0.05, alpha = 1)  +
  # geom_density2d(data = cetaceans_mapping_sp_small %>% filter(Findings.of.Human.Interaction == 'Y'), aes(x = long_corr, y = lat_corr, col = 'HI cases'), bins = 3, size = .5) +
  geom_density2d(data = cetaceans_mapping_sp_small, 
                 aes(x = long_corr, y = lat_corr), col = 'black', bins = 3, size = .5) +  
  #scale_alpha(range = c(0, 0.1), guide = FALSE) +
  xlab("") + ylab("") +
  facet_wrap(~ Cetacean.Common.Name, strip.position = "right") +
  theme_classic() +
   theme(plot.margin = unit(c(0, -5, 0, -5), "mm"),
    axis.line = element_blank(),
    strip.text = element_text(size = 8),
    strip.background = element_blank(),
    legend.title = element_blank(),
    legend.text = element_text(size = 16),
    panel.border = element_rect(colour = "black", fill = NA, size = 1)) +
  scale_color_manual(values = c("black", "red"))

ggsave(file = 'strands_species.png', strands_species, device = 'png', height = 8.5, width = 11, units = 'in', dpi = 1000)

# strands_species_seas_grays <- ggplot(pnw_state_outline) +
# geom_polygon(aes(x = long, y = lat, group = group), fill = "grey93", color = "grey50", size = 0.2) + 
#   coord_fixed(1, ylim = c(42.3, 49.15), xlim = c(-125, -121.8)) + 
#   geom_point(data = cetaceans_mapping_sp_small %>% filter(Cetacean.Common.Name %in% c('Gray whale')),
#            aes(x = long_corr, y = lat_corr), col = 'grey40', size = 1, alpha = 1)  +
#   geom_density2d(data = cetaceans_mapping_sp_small %>%
#                    filter(Cetacean.Common.Name %in% c('Gray whale')),
# aes(x = long_corr, y = lat_corr), col = 'black', bins = 3, size = .5) +  
#   #scale_alpha(range = c(0, 0.1), guide = FALSE) +
#   xlab("") + ylab("") +
#   facet_grid(Cetacean.Common.Name ~ Season) +
#   theme_classic() +
#    theme(plot.margin = unit(c(0, -5, 0, -5), "mm"),
#     axis.line = element_blank(),
#     strip.text = element_text(size = 10, face = 'bold'),
#     strip.background = element_blank(),
#     axis.text = element_blank(),
#     axis.ticks = element_blank(),
#     legend.title = element_blank(),
#     legend.text = element_text(size = 10),
#     panel.border = element_rect(colour = "black", fill = NA, size = 1)) +
#   scale_color_manual(values = c("black", "red"))
# 
# ggsave(file = 'strands_species_seas1.png', strands_species_seas1, device = 'png', height = 8.5, width = 11, units = 'in', dpi = 1000)

strands_species_seas_all <- ggplot(pnw_state_outline) +
geom_polygon(aes(x = long, y = lat, group = group), fill = "grey93", color = "grey50", size = 0.2) + 
  coord_fixed(1, ylim = c(42.3, 49.15), xlim = c(-125, -121.8)) + 
  geom_point(data = cetaceans_mapping_sp_smaller,
           aes(x = long_corr, y = lat_corr), col = 'grey40', size = 1, alpha = 1)  +
  geom_density2d(data = cetaceans_mapping_sp_smaller,
aes(x = long_corr, y = lat_corr), col = 'black', bins = 3, size = .5) +  
  #scale_alpha(range = c(0, 0.1), guide = FALSE) +
  xlab("") + ylab("") +
  facet_grid(Cetacean.Common.Name ~ Season) +
  theme_classic() +
   theme(plot.margin = unit(c(0, -5, 0, -5), "mm"),
    axis.line = element_blank(),
    strip.text = element_text(size = 10, face = 'bold'),
    strip.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.title = element_blank(),
    legend.text = element_text(size = 10),
    panel.border = element_rect(colour = "black", fill = NA, size = 1)) +
  scale_color_manual(values = c("black", "red"))

# strands_species_seas_HI1 <- ggplot(pnw_state_outline) +
# geom_polygon(aes(x = long, y = lat, group = group), fill = "grey93", color = "grey50", size = 0.2) + 
#   coord_fixed(1, ylim = c(42.3, 49.15), xlim = c(-125, -121.8)) + 
#   geom_density2d(data = cetaceans_mapping_sp_small %>%
#                    filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA') %>%
#                    filter(Cetacean.Common.Name %in%
#                             # c('Northern fur seal', 'Northern elephant seal', 'Guadalupe fur seal')),
#                             c('California sea lion', 'Harbor seal', 'Steller sea lion')),
#                  aes(x = long_corr, y = lat_corr), col = 'red', bins = 3, size = .5) +
#   # geom_density2d(data = cetaceans_mapping_sp_small %>%
#   #                  filter(Cetacean.Common.Name %in% 
#   #                           c('Northern fur seal', 'Guadalupe fur seal', 'Northern elephant seal')),
#   #                           #c('California sea lion', 'Harbor seal', 'Steller sea lion')),
#                  # aes(x = long_corr, y = lat_corr), col = 'black', bins = 3, size = .5) +
#   xlab("") + ylab("") +
#   facet_grid(Cetacean.Common.Name ~ Season) +
#   theme_classic() +
#    theme(plot.margin = unit(c(0, -5, 0, -5), "mm"),
#     axis.line = element_blank(),
#     strip.text = element_text(size = 16, face = 'bold'),
#     strip.background = element_blank(),
#     axis.text = element_blank(),
#     axis.ticks = element_blank(),
#     legend.title = element_blank(),
#     legend.text = element_text(size = 10),
#     panel.border = element_rect(colour = "black", fill = NA, size = 1))

```

```{r}
#static maps inland only 

# merge <- cetaceans_mapping_sp %>% group_by(Cetacean.Common.Name) %>%
#   summarize(cnt = n_distinct(National.Database.Number))
# 
# # cetaceans_mapping_sp_small_in <- cetaceans_mapping_sp %>%
# #   merge(merge, by = 'Cetacean.Common.Name') %>%
# #   filter(Cetacean.Common.Name != 'Rissos' & Cetacean.Common.Name != 'Hybrid') %>%
# #   filter(cnt > 1 & Cetacean.Common.Name != 'Other' & !grepl('Blain', Cetacean.Common.Name))
# 
# strands_species_in <- ggplot(pnw_state_outline) +
# geom_polygon(aes(x = long, y = lat, group = group), fill = "grey93", color = "grey50", size = 0.2) + 
#   coord_fixed(1, ylim = c(47, 49.15), xlim = c(-125, -121.8)) + 
#   geom_point(data = cetaceans_mapping_sp_small,
#              aes(x = long_corr, y = lat_corr), col = 'grey40', size = 0.05, alpha = 1)  +
#   # geom_density2d(data = cetaceans_mapping_sp %>% filter(Findings.of.Human.Interaction == 'Y'), aes(x = long_corr, y = lat_corr, col = 'HI cases'), bins = 3, size = .5) +
#   geom_density2d(data = cetaceans_mapping_sp_small, 
#                  aes(x = long_corr, y = lat_corr), col = 'black', bins = 3, size = .5) +  
#   #scale_alpha(range = c(0, 0.1), guide = FALSE) +
#   xlab("") + ylab("") +
#   facet_wrap(~ Cetacean.Common.Name, strip.position = "right") +
#   theme_classic() +
#    theme(plot.margin = unit(c(0, 0, 0, 0), "mm"),
#     axis.line = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(),
#     strip.text = element_text(size = 7.5),
#     strip.background = element_blank(),
#     legend.title = element_blank(),
#     legend.text = element_text(size = 16),
#     panel.border = element_rect(colour = "black", fill = NA, size = 1)) +
#   scale_color_manual(values = c("black", "red"))
# 
# ggsave(file = 'strands_species_in.png', strands_species_in, device = 'png', height = 8.5, width = 11, units = 'in', dpi = 1000)
# 
# strands_in <- ggplot(pnw_state_outline) +
# geom_polygon(aes(x = long, y = lat, group = group), fill = "grey93", color = "grey50", size = 0.2) + 
#   coord_fixed(1, ylim = c(47, 49.15), xlim = c(-125, -121.8)) + 
#   # geom_point(data = cetaceans_mapping_sp %>% filter(Water.Body == 'Inland_WA'),
#   #            aes(x = Longitude, y = Latitude), col = 'grey40', size = 0.05, alpha = 1)  +
#   geom_density2d(data = cetaceans_mapping_sp %>% filter(Findings.of.Human.Interaction == 'Y')
#                  %>% filter(Water.Body == 'Inland_WA'), aes(x = long_corr, y = lat_corr, col = 'HI cases'), bins = 3, size = .5) +
#   geom_density2d(data = cetaceans_mapping_sp  %>% filter(Water.Body == 'Inland_WA'), 
#                  aes(x = long_corr, y = lat_corr, col = "All cases"), bins = 3, size = .5) +  
#   #scale_alpha(range = c(0, 0.1), guide = FALSE) +
#   xlab("") + ylab("") +
#   #facet_wrap(~ Cetacean.Common.Name, strip.position = "right") +
#   theme_classic() +
#    theme(plot.margin = unit(c(0, 0, 0, 0), "mm"), legend.position = 'top',
#     axis.line = element_blank(), 
#     strip.text = element_text(size = 8),
#     strip.background = element_blank(),
#     legend.title = element_blank(),
#     legend.text = element_text(size = 12),
#     panel.border = element_rect(colour = "black", fill = NA, size = 1)) +
#   scale_color_manual(values = c("black", "red"))
# 
# ggsave(file = 'strands_in.png', strands_in, device = 'png', height = 8.5, width = 11, units = 'in', dpi = 1000)
# 
# # strands_species_seas_in <- ggplot(pnw_state_outline) +
# # geom_polygon(aes(x = long, y = lat, group = group), fill = "grey93", color = "grey50", size = 0.2) + 
# #   coord_fixed(1, ylim = c(42.3, 49.15), xlim = c(-125, -121.8)) + 
# #   geom_point(data = cetaceans_mapping_sp_small %>% filter(Cetacean.Common.Name %in% c('Gray whale')),
# #            aes(x = long_corr, y = lat_corr), col = 'grey40', size = 0.05, alpha = 1)  +
# #   # geom_density2d(data = cetaceans_mapping_sp_small %>% 
# #   #                  filter(Findings.of.Human.Interaction == 'Y') %>%
# #   #                 filter(Cetacean.Common.Name %in% c('Gray whale')), aes(x = long_corr, y = lat_corr), bins = 4, size = .5) +
# #   geom_density2d(data = cetaceans_mapping_sp_small %>%
# #                    filter(Cetacean.Common.Name %in% c('Gray whale')),
# # aes(x = long_corr, y = lat_corr), col = 'black', bins = 4, size = .5) +  
# #   #scale_alpha(range = c(0, 0.1), guide = FALSE) +
# #   xlab("") + ylab("") +
# #   facet_grid(Cetacean.Common.Name ~ Season) +
# #   theme_classic() +
# #    theme(plot.margin = unit(c(0, -5, 0, -5), "mm"),
# #     axis.line = element_blank(),
# #     strip.text = element_text(size = 10, face = 'bold'),
# #     strip.background = element_blank(),
# #     axis.text = element_blank(),
# #     axis.ticks = element_blank(),
# #     legend.title = element_blank(),
# #     legend.text = element_text(size = 10),
# #     panel.border = element_rect(colour = "black", fill = NA, size = 1)) +
# #   scale_color_manual(values = c("black", "red"))
# # 
# # ggsave(file = 'strands_species_seas_in.png', strands_species_seas_in, device = 'png', height = 8.5, width = 11, units = 'in', dpi = 1000)

```


```{r species seas gif}

strands_species_seas <- ggplot(pnw_state_outline) +
geom_polygon(aes(x = long, y = lat, group = group), fill = "grey93", color = "grey50", size = 0.2) + 
  coord_fixed(1, ylim = c(42.3, 49.15), xlim = c(-125, -121.8)) + 
  geom_point(data = cetaceans_mapping_sp_small,
             aes(x = long_corr, y = lat_corr, group = Season, 
                     frame = Season, cumulative = F), col = 'grey40', size = 0.05, alpha = 1)  +
  geom_density2d(data = cetaceans_mapping_sp_small, 
                 aes(x = long_corr, y = lat_corr, group = Season, 
                     frame = Season, cumulative = F), col = 'black', bins = 2) +
  #scale_alpha(range = c(0, 0.1), guide = FALSE) +
  xlab("") + ylab("") +
  facet_wrap(~ Cetacean.Common.Name, strip.position = "right") +
  #theme_classic() +
  theme(
    plot.margin = unit(c(10, -10, 0, -10), "mm"),
    axis.line = element_blank(), 
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    legend.text = element_text(size = 14, face = 'bold'),
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    strip.background = element_blank(),
    legend.position = 'top', legend.title = element_blank(),
    panel.border = element_rect(colour = "black", fill = NA, size = 1)) #+
  #scale_color_manual(values = c("black", "red"))

gganimate(strands_species_seas, interval = 2.0, filename = "~/Documents/R/Cet_Strandings/manuscript_figs/strands_species_an_seas.gif") 
```


```{r annual hotspots}

#All combined species

all_strands_year_an <- ggplot(pnw_state_outline) +
geom_polygon(aes(x = long, y = lat, group = group), fill = "grey93", color = "grey50", size = 0.2) +
  coord_fixed(1, ylim = c(42.3, 49.15), xlim = c(-125, -121.8)) +
  geom_point(data = cetaceans_mapping_sp_small, aes(x = long_corr, y = lat_corr, group = Year.of.Observation, frame = Year.of.Observation, cumulative = F), color = 'grey50', size = 0.2, alpha = 0.8)  +
# geom_density2d(data = cetaceans_mapping_sp_small %>%
#                  filter(Findings.of.Human.Interaction == 'Y'), aes(x = long_corr, y = lat_corr, group = Year.of.Observation, frame = Year.of.Observation, cumulative = F, col = 'HI Cases'), bins = 4) +
  geom_density2d(data = cetaceans_mapping_sp_small, aes(x = long_corr, y = lat_corr, group = Year.of.Observation, frame = Year.of.Observation, cumulative = F), col = "black", bins = 3) +
  #scale_fill_gradient(low = "yellow", high = "red", guide = FALSE) +
  #scale_alpha(range = c(0, 0.1), guide = FALSE) +
  xlab("") + ylab("") + facet_wrap(~Year.of.Observation) +
  #theme_classic() +
  theme(
    plot.margin = unit(c(10, -10, 0, -10), "mm"),
    axis.line = element_blank(), 
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    legend.text = element_text(size = 20, face = 'bold'),
    plot.title = element_text(size = 20, face = "bold", hjust = 0.5),
    strip.background = element_blank(),
    legend.position = 'top', legend.title = element_blank(),
    panel.border = element_rect(colour = "black", fill = NA, size = 1)) + 
  scale_color_manual(values = c("black", "red")) 

gganimate(all_strands_year_an, interval = 1, filename = "~/Documents/Research/Cet_Strandings/Figures/all_strands_year_an.gif")

#Faceted for three species
all_strands_year_an_nohp <- ggplot(pnw_state_outline) +
geom_polygon(aes(x = long, y = lat, group = group), fill = "grey93", color = "grey50", size = 0.2) +
  coord_fixed(1, ylim = c(42.3, 49.15), xlim = c(-125, -121.8)) +
  geom_point(data = cetaceans_mapping_sp_small  %>% 
               filter(Cetacean.Common.Name != 'Harbor porpoise'), 
             aes(x = long_corr, y = lat_corr, group = Year.of.Observation, 
                 frame = Year.of.Observation, cumulative = F), color = 'grey50', size = 0.2, alpha = 0.8)  + 
  geom_density2d(data = cetaceans_mapping_sp  %>% 
                 filter(Cetacean.Common.Name != 'Harbor porpoise'), 
                 aes(x = long_corr, y = lat_corr, group = Year.of.Observation, 
                     frame = Year.of.Observation, cumulative = F), col = 'black', bins = 2) +
  # stat_density2d(data = cetaceans_mapping  %>%
  #                filter(Cetacean.Common.Name %in% c('Harbor porpoise', 'Gray whale', 'Dalls porpoise')), 
  #                aes(x = long_corr, y = lat_corr, group = Year.of.Observation, 
  #                    frame = Year.of.Observation, cumulative = F, fill = ..level.., alpha = ..level..), 
  #                size = 0.01, bins = 100, geom = "polygon") +
  scale_fill_gradient(low = "yellow", high = "red", guide = FALSE) +
  scale_alpha(range = c(0, 0.1), guide = FALSE) +
  xlab("") + ylab("") +
  facet_wrap(~Year.of.Observation) +
  theme_classic() +
  theme(strip.text = element_text(size = 12, face = 'bold'),
    plot.margin = unit(c(10, 5, 0, 0), "mm"),
    axis.line = element_blank(),
    legend.text = element_text(size = 15),
    plot.title = element_text(size = 20, face = "bold", hjust = 0.5),
    strip.background = element_blank(),
    axis.text = element_blank(), axis.ticks = element_blank(),
    legend.position = 'top', legend.title = element_blank(),
    panel.border = element_rect(colour = "black", fill = NA, size = 1)) 

all_strands_year_an_sp_hp <- ggplot(pnw_state_outline) +
geom_polygon(aes(x = long, y = lat, group = group), fill = "grey93", color = "grey50", size = 0.2) +
  coord_fixed(1, ylim = c(42.3, 49.15), xlim = c(-125, -121.8)) +
  geom_point(data = cetaceans_mapping_sp_small  %>% 
               filter(Cetacean.Common.Name == 'Harbor porpoise'), 
             aes(x = long_corr, y = lat_corr, group = Year.of.Observation, 
                 frame = Year.of.Observation, cumulative = F), color = 'grey50', size = 0.2, alpha = 0.8)  + 
  geom_density2d(data = cetaceans_mapping_sp  %>% 
                 filter(Cetacean.Common.Name == 'Harbor porpoise'), 
                 aes(x = long_corr, y = lat_corr, group = Year.of.Observation, 
                     frame = Year.of.Observation, cumulative = F), col = 'black', bins = 2) +
  # stat_density2d(data = cetaceans_mapping  %>%
  #                filter(Cetacean.Common.Name %in% c('Harbor porpoise', 'Gray whale', 'Dalls porpoise')), 
  #                aes(x = long_corr, y = lat_corr, group = Year.of.Observation, 
  #                    frame = Year.of.Observation, cumulative = F, fill = ..level.., alpha = ..level..), 
  #                size = 0.01, bins = 100, geom = "polygon") +
  scale_fill_gradient(low = "yellow", high = "red", guide = FALSE) +
  scale_alpha(range = c(0, 0.1), guide = FALSE) +
  xlab("") + ylab("") +
  facet_wrap(~Year.of.Observation) +
  theme_classic() +
  theme(strip.text = element_text(size = 12, face = 'bold'),
    plot.margin = unit(c(10, 5, 0, 0), "mm"),
    axis.line = element_blank(),
    legend.text = element_text(size = 15),
    plot.title = element_text(size = 20, face = "bold", hjust = 0.5),
    strip.background = element_blank(),
    axis.text = element_blank(), axis.ticks = element_blank(),
    legend.position = 'top', legend.title = element_blank(),
    panel.border = element_rect(colour = "black", fill = NA, size = 1)) 

gganimate(all_strands_year_an_sp, interval = 1, filename = "~/Documents/R/Cet_Strandings/Figures/all_strands_year_an_spB.gif")

```

```{r unused figures}

#from figure, before switch to ggplot

# #HI type facet map
# HI_type_facet <- ggmap(get_googlemap(center = 'Portland, OR', maptype = "terrain", zoom = 6, size = c(640, 640), style = c(feature = "all", element = "labels", visibility = "off"))) +
#   geom_point(data = cetaceans_mapping_HI, aes(x = long_corr, y = lat_corr), color = 'grey20', size = 0.2, alpha = 0.8)  +
#   geom_density2d(data = cetaceans_mapping_HI, aes(x = long_corr, y = lat_corr), bins = 5, col = 'grey30') +
#   scale_alpha(range = c(0, 0.1), guide = FALSE) +
#   xlab("") + ylab("") +
#   facet_wrap(~ Interaction.Type) +
#   scale_x_continuous(limits = c(-127, -120)) + scale_y_continuous(limits = c(42.8, 49.05)) +
#    theme(plot.margin = unit(c(0, -10, 0, -10), "mm"),
#     axis.line = element_blank(),
#     #axis.ticks = element_blank(),
#     #axis.text = element_blank(),
#     strip.text = element_text(size = 10),
#     strip.background = element_blank(),
#     panel.border = element_rect(colour = "black", fill = NA, size = 1))
#   
# figs("HI_type_facet", caption = "Strandings (grey points) and kernel density hotspot contour lines showing hotspots of human interaction cases, with fisheries and boat collisions distributed throughout inland Washington waters and at the mouth of the Columbia River, and a gunshot wound cluster centered at the mouth of the Columbia River.")
# 
# #HI and strandings - species facet, red and black
# HIstrands_species <-
#  ggmap(get_googlemap(center = 'Portland, OR', maptype = "terrain", zoom = 6, size = c(640, 640), style = c(feature = "all", element = "labels", visibility = "off"))) +
#   geom_point(data = cetaceans_mapping_sp %>% filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA'), 
#              aes(x = long_corr, y = lat_corr), col = 'grey35', size = 0.2, alpha = 0.5)  +
#   geom_density2d(data = cetaceans_mapping_sp %>% filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA'), aes(x = long_corr, y = lat_corr, weight = weight), bins = 3, col = 'red') +
#   geom_density2d(data = cetaceans_mapping_sp, aes(x = long_corr, y = lat_corr, weight = weight), bins = 2, col = 'grey20') +  scale_alpha(range = c(0, 0.1), guide = FALSE) +
#   xlab("") + ylab("") +
#   facet_wrap(~ Cetacean.Common.Name) +
#   scale_x_continuous(limits = c(-127, -120)) + scale_y_continuous(limits = c(42.9, 48.95)) +
#    theme(plot.margin = unit(c(0, -5, 0, -5), "mm"),
#     axis.line = element_blank(),
#     #axis.ticks = element_blank(),
#     #axis.text = element_blank(),
#     strip.text = element_text(size = 10),
#     strip.background = element_blank(),
#     panel.border = element_rect(colour = "black", fill = NA, size = 1))
# 
# figs("HIstrands_species", caption = "Strandings (grey points) and kernel density hotspot contour lines showing overlapping hotspots for all strandings (black) and human interaction cases (red) for all species, with hotspots occurring throughout inland Washington for harbor seals and along the outer coast near the mouth of the Columbia River for the other species.")



#county lines
# counties <- tolower(unique(cetaceans_mapping_sp$County)) 
# 
# pnw_outline <- map_data("county", region = c("oregon", "washington")) %>%
#   filter(subregion %in% counties) %>%
#   mutate(subregion = ifelse(region == 'washington' & subregion == 'lincoln', 'NA',
#                             ifelse(region == 'washington' & subregion == 'douglas', 'NA',
#                                    ifelse(region == 'oregon' & subregion == 'jefferson', 'NA',
#                                           ifelse(region == 'washington' & subregion == 'columbia', 'NA', subregion))))) %>%
#   filter(subregion != 'NA')

# pnw_map <- ggplot(pnw_outline) +
# geom_polygon(aes(x = long, y = lat, group = group), fill = "grey", color = "black") + 
#   coord_fixed(1.3) + 
#   geom_point(data = cetaceans_mapping_HI, aes(x = long_corr, y = lat_corr), color = 'grey20', size = 0.2, alpha = 0.8)  +
#   geom_density2d(data = cetaceans_mapping_HI, aes(x = long_corr, y = lat_corr), bins = 5, col = 'grey30') +
#   scale_alpha(range = c(0, 0.1), guide = FALSE) +
#   xlab("") + ylab("") +
#   #facet_wrap(~ Interaction.Type) +
#   scale_x_continuous(limits = c(-127, -120)) + scale_y_continuous(limits = c(42.8, 49.05)) + 
#   #theme_nothing() +
#   theme(plot.margin = unit(c(0, -10, 0, -10), "mm"),
#     axis.line = element_blank(),
#     #axis.ticks = element_blank(),
#     #axis.text = element_blank(),
#     strip.text = element_text(size = 10),
#     strip.background = element_blank(),
#     panel.border = element_rect(colour = "black", fill = NA, size = 1))

#play with qmplot
# test <- qmplot(long_corr, lat_corr, data = cetaceans_mapping_HI,
#                geom = "density2d")


#All strandings - species facet
# allstrands_species <-
#  ggmap(get_googlemap(center = 'Portland, OR', maptype = "terrain", zoom = 6, size = c(640, 640), style = c(feature = "all", element = "labels", visibility = "off"))) +
#   geom_point(data = cetaceans_mapping_sp, aes(x = long_corr, y = lat_corr), color = 'grey40', size = 0.2, alpha = 0.8)  +
#   geom_density2d(data = cetaceans_mapping_sp, aes(x = long_corr, y = lat_corr), bins = 3, col = 'grey20', h = c(5, 0.5)) +
#   # stat_density2d(data = cetaceans_mapping_sp, aes(x = long_corr, y = lat_corr, fill = ..level.., alpha = ..level..), size = 0.1, geom = "polygon") +
#   # scale_fill_gradient(low = "yellow", high = "red", guide = FALSE) +
#   scale_alpha(range = c(0, 0.1), guide = FALSE) +
#   xlab("") + ylab("") +
#   facet_wrap(~ Cetacean.Common.Name) +
#   scale_x_continuous(limits = c(-127, -120)) + scale_y_continuous(limits = c(42.8, 49.05)) +
#    theme(plot.margin = unit(c(0, -5, 0, -5), "mm"),
#     axis.line = element_blank(),
#     axis.ticks = element_blank(),
#     axis.text = element_blank(),
#     strip.text = element_text(size = 10),
#     strip.background = element_blank(),
#     panel.border = element_rect(colour = "black", fill = NA, size = 5))
# 
# figs("allstrands_species", caption = "All stranding cases (grey points) and kernel density hotspot contour lines showing stranding hotspots for each species, with hotspots occurring in the Salish Sea for harbor seals and along the outer coast near the mouth of the Columbia River for the other species.")

#Checking whether hotspots have changed over time - definitely sort of has
# HIstrands_yr <-
#  ggmap(get_googlemap(center = 'Portland, OR', maptype = "terrain", zoom = 6, size = c(640, 640), style = c(feature = "all", element = "labels", visibility = "off"))) +
#   # geom_point(data = cetaceans_mapping_sp %>% filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA'), aes(x = long_corr, y = lat_corr), color = 'grey50', size = 0.3, alpha = 0.5)  +
#   geom_density2d(data = cetaceans_mapping %>% filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA') %>% filter(Year.of.Observation == 1990 |
#                    Year.of.Observation == 1995 |
#                    Year.of.Observation == 2000 | 
#                    Year.of.Observation == 2005 |
#                    Year.of.Observation == 2010 |
#                    Year.of.Observation == 2015), aes(x = long_corr, y = lat_corr), bins = 3, col = 'red') +
#   geom_density2d(data = cetaceans_mapping %>% 
#                    filter(Year.of.Observation == 1990 |
#                    Year.of.Observation == 1995 |
#                    Year.of.Observation == 2000 | 
#                    Year.of.Observation == 2005 |
#                    Year.of.Observation == 2010 |
#                    Year.of.Observation == 2015), aes(x = long_corr, y = lat_corr), bins = 2, col = 'grey20') +
#   scale_alpha(range = c(0, 0.1), guide = FALSE) +
#   xlab("") + ylab("") +
#   facet_wrap(~ Year.of.Observation) +
#   scale_x_continuous(limits = c(-127, -120)) + scale_y_continuous(limits = c(42, 49.65)) +
#    theme(plot.margin = unit(c(0, -5, 0, -5), "mm"),
#     axis.line = element_blank(),
#     axis.ticks = element_blank(),
#     axis.text = element_blank(),
#     strip.text = element_text(size = 10),
#     strip.background = element_blank(),
#     panel.border = element_rect(colour = "black", fill = NA, size = 5))


#Option with overlapping HI types
# HI_overlap <-
#  ggmap(get_googlemap(center = 'Portland, OR', maptype = "terrain", zoom = 6, size = c(640, 640), style = c(feature = "all", element = "labels", visibility = "off"))) +
#   geom_point(data = cetaceans_mapping_HI, 
#              aes(x = long_corr, y = lat_corr), color = 'grey30', size = 0.2, alpha = 0.8)  +
#   geom_density2d(data = cetaceans_mapping_HI, aes(x = long_corr, y = lat_corr, col = Interaction.Type), bins = 4, size = .8) +
#   scale_alpha(range = c(0, 0.1), guide = FALSE) +
#   xlab("") + ylab("") +
#   #facet_wrap(~ Interaction.Type) +
#   scale_x_continuous(limits = c(-127, -120)) + scale_y_continuous(limits = c(42.8, 49.05)) +
#    theme(legend.position = 'top', legend.title = element_blank(),
#     plot.margin = unit(c(0, -5, 0, -5), "mm"),
#     axis.line = element_blank(),
#     axis.ticks = element_blank(),
#     axis.text = element_blank(),
#     strip.text = element_text(size = 10),
#     strip.background = element_blank(),
#     panel.border = element_rect(colour = "black", fill = NA, size = 5)) +
#   scale_color_manual(values = color1)
# 
# figs("HI_overlap", caption = "Strandings (grey points) and kernel density hotspot contour lines showing hotspots of human interaction cases, with fisheries and boat collisions distributed throughout the Salish Sea and at the mouth of the Columbia River, and gunshot wound cluster centered at the mouth of the Columbia River.")


```
