---
title: 'Cetacean Stranding and Oceanographic Index Modeling Analysis and Research Questions'
author: Amanda Warlick, Dec 2018
output:
  word_document

---

```{r, include = F}
knitr::opts_chunk$set(echo = T, warning = FALSE, message = FALSE)
```
 

```{r packages and data, include = F, echo = F}
library(ggplot2)
library(tidyr)
#library(ggmap)
library(data.table)
#library(cowplot)
library(knitr)
library(reshape2)
library(stringr)
library(magrittr)
library(scales)
library(stats) 
library(MASS) #glm.nb(), stepAIC()
library(dplyr)
library(leaps) # regsubsets() 
library(corrplot)
library(Hmisc) # rcorr()

```

```{r}

setwd("~/Documents/Research/Cet_Strandings")

# Data Load 
###############################################################################
# pinnipeds_ocean <- read.csv("pinnipeds_ocean.csv", header = TRUE, na.strings = "NA", stringsAsFactors = FALSE) %>%
#   transform(Period = ifelse(Year.of.Observation < 2005, 'Pre_Prescott', 'Post_Prescott'))

cetaceans_ocean <- read.csv("cetaceans_ocean.csv", header = TRUE, na.strings = "NA", stringsAsFactors = FALSE) %>%
  transform(Period = ifelse(Year.of.Observation < 2005, 'Pre_Prescott', 'Post_Prescott')) 

#Load dataframes from PinnipedsandENSO.Rmd and CetaceansandENSO.Rmd

#setwd("~/Documents/Research/Strandings/ENSO_Mapping/Env Data")

fish <- read.csv("fish_full.csv", header = TRUE, na.strings = "NA", stringsAsFactors = FALSE)

ocean_full <- read.csv("ocean_full_cet.csv", header = TRUE, na.strings = "NA", stringsAsFactors = FALSE)

#Ocean only variables for correlation exploration
ocean_corr <- ocean_full %>%
  merge(fish, by = c('Year.of.Observation', 'Month.of.Observation'), all = T) %>%
  #dplyr::select(-matches("Date")) %>%
  dplyr::select(-matches("ENSO_cat")) %>%
  dplyr::select(-c(Month.of.Observation, Year.of.Observation))

setwd("~/Documents/Research/Cet_Strandings")

#Monthly anomalies separate species
monthly_anom <- read.csv("monthly_anom.csv", header = TRUE, na.strings = "NA", stringsAsFactors = FALSE) %>%
  transform(Period = ifelse(Year.of.Observation < 2004, 'Pre_Prescott', 'Post_Prescott')) %>%
  transform(type = ifelse(Cetacean.Common.Name %in% c('Striped dolphin', 'Long-beaked common dolphin',
                                                      'Killer whale', 'Rissos', 'Pacific white-sided dolphin',
                                                      'Bottlenose dolphin', 'Short-beaked common dolphin', 
                                                      'Northern right whale dolphin'), 'Dolphinidae', 'Other'))
#Monthly anomalies combined species
monthly_anom_comb <- read.csv("monthly_anom_comb.csv", header = TRUE, na.strings = "NA", stringsAsFactors = FALSE) %>%
  transform(Period = ifelse(Year.of.Observation < 2004, 'Pre_Prescott', 'Post_Prescott'))
#Annual anomalies separate species
annual_anom <- read.csv("annual_anom.csv", header = TRUE, na.strings = "NA", stringsAsFactors = FALSE) %>%
  transform(Period = ifelse(Year.of.Observation < 2004, 'Pre_Prescott', 'Post_Prescott'))
#Annual anomalies combined species
annual_anom_comb <- read.csv("annual_anom_comb.csv", header = TRUE, na.strings = "NA", stringsAsFactors = FALSE) %>%
  transform(Period = ifelse(Year.of.Observation < 2004, 'Pre_Prescott', 'Post_Prescott'))

flattenCorrMatrix <- function(cormat, pmat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
    )
}


```

```{r ocean cor}

ocean_corr_small <- ocean_corr %>% 
  dplyr::select(-matches("lag")) %>%
  dplyr::select(-matches("44")) %>%
  dplyr::select(-matches("45")) %>%
  rename(Upwelling = Upwelling_39, SST = SST_39, SST_anom = SST_39_anom, Wind = Wind_39) %>%
  dplyr::select(MEI, PDO, NPGO, SST, SST_anom, Upwelling, Wind, CBA_North, CBA_South)

ocean_corr_0vs1 <- ocean_corr %>%
  dplyr::select(-matches("44")) %>%
  dplyr::select(-matches("45")) %>%
  rename(Upwelling = Upwelling_39, SST = SST_39, SST_anom = SST_39_anom, Wind = Wind_39) %>%
  dplyr::select(-matches("lag2")) %>%
  dplyr::select(-matches("lag3")) 

ocean_corr_0vs2 <- ocean_corr %>%
  dplyr::select(-matches("lag1")) %>%
  dplyr::select(-matches("lag3")) 

ocean_corr_0vs3 <- ocean_corr %>%
  dplyr::select(-matches("lag1")) %>%
  dplyr::select(-matches("lag2")) 

ocean_corr_small_buoys <- ocean_corr %>%
  dplyr::select(-matches("lag")) 

# cor <- cor(ocean_corr_small, use = "pairwise.complete.obs")
# cor <- cor(ocean_corr_med, use = "pairwise.complete.obs")

cor_test_small <- rcorr(as.matrix(ocean_corr_small))
flattenCorrMatrix(cor_test_small$r, cor_test_small$P)

cor_test_small_buoys <- rcorr(as.matrix(ocean_corr_small_buoys))

cor_test_0vs1 <- rcorr(as.matrix(ocean_corr_0vs1))
cor_test_0vs2 <- rcorr(as.matrix(ocean_corr_0vs2))
cor_test_0vs3 <- rcorr(as.matrix(ocean_corr_0vs3))

#In general, 
## --- Upwelling 39 and 45 are correlated, likewise Wind 39 and 44, SST 39 and 44 less so
## --- SST and SST_anom of same buoy are correlated, less so for opposite buoy pairs
## --- Upwelling and Wind are inversely correlated
## --- PDO and MEI correlated
## --- CBA North and South inversely correlated, and correlated to MEI etc. and SST_anoms, but less so with SST, Upwell, and Wind
small <- corrplot(cor_test_small$r, type = "lower", order = "original", p.mat = cor_test_small$P, 
         insig = "blank", sig.level = 0.01, tl.col = "black", tl.cex = .9, number.cex = .2)
lag0vs1 <- corrplot(cor_test_0vs1$r, type = "lower", order = "original", p.mat = cor_test_0vs1$P, 
         insig = "blank", sig.level = 0.01, tl.col = "black", tl.cex = .7, number.cex = .7)
#SST and SST_anom_lag2s are correlated
lag1vs2 <- corrplot(cor_test_0vs2$r, type = "lower", order = "original", p.mat = cor_test_0vs2$P, 
         insig = "blank", sig.level = 0.01, tl.col = "black", tl.cex = .7, number.cex = .7)
lag2vs3 <- corrplot(cor_test_0vs3$r, type = "lower", order = "original", p.mat = cor_test_0vs3$P, 
         insig = "blank", sig.level = 0.01, tl.col = "black", tl.cex = .7, number.cex = .7)

corrplot(cor_test_small_buoys$r, type = "lower", order = "original", p.mat = cor_test_small_buoys$P, 
         insig = "blank", sig.level = 0.001, tl.col = "black", tl.cex = .9, number.cex = .2)

```

```{r chow test}

r.reg <- lm(cnt_all ~ Year.of.Observation, data = annual_anom_comb)
ur.reg1 <- lm(cnt_all ~ Year.of.Observation, data = annual_anom_comb %>% filter(Period == 'Pre_Prescott'))
ur.reg2 <- lm(cnt_all ~ Year.of.Observation, data = annual_anom_comb %>% filter(Period != 'Pre_Prescott'))
                                            
## review the regression results
summary(r.reg)
summary(ur.reg1)
summary(ur.reg2)
 
## Calculate sum of squared residuals for each regression
SSR <- NULL
SSR$r <- r.reg$residuals^2
SSR$ur1 <- ur.reg1$residuals^2
SSR$ur2 <- ur.reg2$residuals^2
 
## K is the number of regressors in our model
K <- r.reg$rank
 
## Computing the Chow test statistic (F-test)
numerator <- (sum(SSR$r) - (sum(SSR$ur1) + sum(SSR$ur2)))/K
denominator <- (sum(SSR$ur1) + sum(SSR$ur2)) / (nrow(annual_anom_comb) - 2*K)
chow = numerator/denominator
chow
 
## Calculate P-value
1-pf(chow, K, (nrow(annual_anom_comb) - 2*K))

## Plot the results
ggplot(annual_anom_comb, aes(Year.of.Observation, cnt_all)) +
  geom_point() +
  geom_smooth(method = 'lm', se = F, col = 'grey50', linetype = 'dashed', size = 0.7) +
  geom_smooth(aes(group = Period), method = 'lm', se = F, linetype = 'dashed', col = 'red', size = 0.7) + 
  xlab("") + ylab("Total Strandings")

ggplot(annual_anom_comb, aes(Year.of.Observation, cnt_HI)) +
  geom_point() +
  geom_smooth(method = 'lm', se = F, col = 'grey50', linetype = 'dashed', size = 0.7) +
  geom_smooth(aes(group = Period), method = 'lm', se = F, linetype = 'dashed', col = 'red', size = 0.7) + 
  xlab("") + ylab("HI Cases")

#Strucchange option - comes up with same pvalue as manual calculation, 2003 breakpoint
sctest(cnt_all ~ Year.of.Observation, type = "Chow", point = 15, data = annual_anom_comb)
sctest(strand_anom ~ Year.of.Observation, type = "Chow", point = 15, data = annual_anom_comb)

sctest(cnt_HI ~ Year.of.Observation, type = "Chow", point = 15, data = annual_anom_comb)
sctest(strand_anom_HI ~ Year.of.Observation, type = "Chow", point = 15, data = annual_anom_comb)
```

```{r references}

#http://thestatsgeek.com/2014/04/26/deviance-goodness-of-fit-test-for-poisson-regression/
pchisq(deviance(nb), df.residual(nb), lower.tail = F) # pvalue = 0.33, which means model is an okay fit?
# pchisq(deviance(qp), df.residual(qp), lower.tail = F) # pvalue is small - not a good fit, reject null hypothesis that model is well-constructed

#https://www3.nd.edu/~rwilliam/stats3/CountModels.pdf #good, but code is stata

#https://www.theanalysisfactor.com/poisson-or-negative-binomial-using-count-model-diagnostics-to-select-a-model/ residual plots and nb versus poisson

#https://stats.stackexchange.com/questions/128926/how-to-interpret-parameter-estimates-in-poisson-glm-results

#https://stats.stackexchange.com/questions/234057/interpretation-of-slope-estimate-of-poisson-regression

#https://www.zoology.ubc.ca/~schluter/R/fit-model/#glmregression

#http://plantecology.syr.edu/fridley/bio793/glm.html

```

##Research Questions

1. Are strandings increasing over time?

```{r}
### Are total annual combined strandings or of each species increasing over time?  
 
#Could use lm() to derive and report slope of line, glm for test statistics/p-values, or glm and reporting fold increase per decade.

## (a) All strandings, combined species
data_by_year <- cetaceans_ocean %>% 
  group_by(Year.of.Observation) %>%
  dplyr::summarize(cnt = n_distinct(National.Database.Number)) 

sctest_data <- data_by_year %>%
  arrange(cnt)

sctest(Year.of.Observation ~ cnt, type = "Chow", point = 12, data = sctest_data)

# GLM with Poisson
summary(glm(cnt ~ Year.of.Observation, family = poisson(link = log), data = data_by_year))
#slope of line =  exp(0.0383*x) = y = 1.039^x = 3.9%/year

#Negative binomial GLM
summary(glm.nb(cnt ~ Year.of.Observation, data = data_by_year))
#slope of line =  exp(0.039900*x) = y = 1.040^x = 4.0%/year

## (b) All strandings, separate species
all_sp <- cetaceans_ocean %>%
  filter(Cetacean.Common.Name %in% 
           c('Harbor porpoise', 'Gray whale', 'Humpback whale', 'Striped dolphin', 'Dalls porpoise')) %>%
  group_by(Year.of.Observation, Cetacean.Common.Name) %>%
  dplyr::summarize(cnt = n_distinct(National.Database.Number))

###Harbor porp
hp <- all_sp[all_sp$Cetacean.Common.Name == 'Harbor porpoise', 'cnt']
mean(hp$cnt)
var(hp$cnt)

#GLM with Poisson
summary(glm(cnt ~ Year.of.Observation, family = poisson(link = log), 
            data = all_sp %>% filter(Cetacean.Common.Name == 'Harbor porpoise'))) # 

#Negative binomial - use to avoid concerns of overdispersion
summary(glm.nb(cnt ~ Year.of.Observation, data = all_sp %>% filter(Cetacean.Common.Name == 'Harbor porpoise'))) # y = exp(0.0563) = 1.0579 = 5.7% per year

###gray
gw <- all_sp[all_sp$Cetacean.Common.Name == 'Gray whale', 'cnt']
mean(gw$cnt) #8.7
var(gw$cnt) #17.2

summary(lm(cnt ~ Year.of.Observation, data = all_sp %>% filter(Cetacean.Common.Name == 'Gray whale')))

#GLM with Poisson
summary(glm(cnt ~ Year.of.Observation, family = poisson(link = log), 
            data = all_sp %>% filter(Cetacean.Common.Name == 'Gray whale'))) # y = 1.1^x

#Negative binomial - use to avoid concerns of overdispersion
summary(glm.nb(cnt ~ Year.of.Observation, data = all_sp %>% filter(Cetacean.Common.Name == 'Gray whale'))) # y = exp(-.00605) = 1.0579 = 5.7% per year




```


1. Are strandings (and or human interaction (HI) cases) for combined or individual species correlated with certain oceanographic indices?


```{r}
 
#All covariates, example using stepAIC

#na.omit() removes all rows with any missing data, glm.nb(keeps rows but removes the single NA value)
fit_step_all <- glm.nb(cnt_all ~ 
          MEI + PDO + NPGO + SST_39 + SST_39_anom + SST_44 + SST_44_anom + Wind_39 + Wind_44 + Upwelling_39 + Upwelling_45 + CBA_North + CBA_South + ENSO_cat + Sard + Anch + Herring + Msquid_N,
          # MEI_lag1 + PDO_lag1 + NPGO_lag1 + SST_39_lag1 + SST_44_lag1 + Wind_39_lag1 + Wind_44_lag1 + Upwelling_39_lag1 + Upwelling_45_lag1 + CBA_North_lag1 + CBA_South_lag1 + SST_39_anom_lag1 + SST_44_anom_lag1 +
          # MEI_lag2 + PDO_lag2 + NPGO_lag2 + SST_39_lag2 + SST_44_lag2 + Wind_39_lag2 + Wind_44_lag2 + Upwelling_39_lag2 + Upwelling_45_lag2 + CBA_North_lag2 + CBA_South_lag2 + SST_39_anom_lag2 + SST_44_anom_lag2 +
          # MEI_lag3 + PDO_lag3 + NPGO_lag3 + SST_39_lag3 + SST_44_lag3 + Wind_39_lag3 + Wind_44_lag3 + Upwelling_39_lag3 + Upwelling_45_lag3 + CBA_North_lag3 + CBA_South_lag3 + SST_39_anom_lag3 + SST_44_anom_lag3, 
      data = na.omit(monthly_anom_comb))
step <- stepAIC(fit_step_all, direction = "backward")
step$anova
# result = cnt_all ~ NOI + SST_39_anom + Upwelling_39 + Herring

```

```{r}
# Separate species 

#based on these means and variances, it seems like poisson would be appropriate for all except hp
month_sumstats <- monthly_anom %>% 
  filter(Cetacean.Common.Name %in% 
           c('Harbor porpoise', 'Gray whale', 'Humpback whale', 'Striped dolphin', 
             'Dalls porpoise', 'Pacific white-sided dolphin')) %>%
  dplyr::select(Year.of.Observation, Month.of.Observation, Cetacean.Common.Name, cnt_all, mean_all) %>%
  group_by(Cetacean.Common.Name) %>%
  dplyr::summarize(mean = mean(cnt_all), var = var(cnt_all))

#main covs: MEI + SST_39 + SST_39_anom + Wind_39 + CBA_North + Sard + Msquid_N +
          # MEI_lag1 + SST_39_lag1 + SST_44_lag1 + Wind_39_lag1 + Upwelling_39_lag1 + SST_44_anom_lag1 +
          #   SST_44_lag2 + Upwelling_45_lag2 + SST_44_anom_lag2 +
          # SST_44_lag3  + Upwelling_39_lag3

#############Harbor porpoise
mod_select <- regsubsets(cnt_all ~ 
          CBA_North + Sard + Msquid_N +
          MEI_lag1 +
            SST_44_lag2, 
          data = monthly_anom %>% filter(Cetacean.Common.Name == 'Harbor porpoise'), 
          nbest = 4, really.big = T)
summary(mod_select)
#w/ fish
nb <- glm.nb(cnt_all ~ 
                       CBA_North + 
                       Sard + 
                       SST_44_lag2 +
                       #SST_39_lag2 +
                       MEI_lag1 + 
                       Msquid_N, 
                    data = monthly_anom %>% filter(Cetacean.Common.Name == 'Harbor porpoise'))
sum <- summary(nb)
pchisq(deviance(sum), df.residual(sum), lower.tail = F) #.53
#lower AIC with CBA and MEI_lag1 (660 versus 700), higher chisq p value without (.53 versus .49)
plot(nb)

#w/o fish
nb <- glm.nb(cnt_all ~ 
                       CBA_North + 
                       #Sard + 
                       SST_44_lag2 +
                       #SST_39_lag2 +
                       MEI_lag1, 
                    data = monthly_anom %>% filter(Cetacean.Common.Name == 'Harbor porpoise'))
sum <- summary(nb)
plot(nb)
pchisq(deviance(nb), df.residual(nb), lower.tail = F)

########Gray whales
mod_select <- regsubsets(cnt_all ~ SST_44 + Upwelling_39 + CBA_North + ENSO_cat + Msquid_N +
         Upwelling_45_lag1 + MEI_lag3,
          data = monthly_anom %>% filter(Cetacean.Common.Name == 'Gray whale'), nbest = 4, really.big = T)
summary(mod_select)

#doesn't matter which MEI val is used; theta error/warning messages
nb <- glm.nb(cnt_all ~ 
                       #SST_44 + 
                       Upwelling_39 + 
                       CBA_North + 
                       #ENSO_cat + 
                       #Msquid_N +
                       #Upwelling_45_lag1 +
                       MEI_lag3, 
          data = monthly_anom %>% filter(Cetacean.Common.Name == 'Gray whale'))
sum <- summary(nb)
plot(nb)
pois <- glm(cnt_all ~ 
                       #SST_44 + 
                       Upwelling_39 + 
                       CBA_North + 
                       #ENSO_cat + 
                       #Msquid_N +
                       #Upwelling_45_lag1 +
                       MEI_lag1, 
          data = monthly_anom %>% filter(Cetacean.Common.Name == 'Gray whale'), family = 'poisson')
sum <- summary(pois)
plot(pois)
pchisq(deviance(sum), df.residual(sum), lower.tail = F) # pvalue = 0.96

#dalls w/o fish
mod_select <- regsubsets(cnt_all ~ 
           SST_39 + SST_39_anom + CBA_North +
          MEI_lag1 + SST_44_anom_lag1 + Upwelling_45_lag2 +
          SST_44_lag3,
          data = monthly_anom %>% filter(Cetacean.Common.Name == 'Dalls porpoise'), nbest = 4, really.big = T)
summary(mod_select)

#w/ fish
nb <- summary(glm.nb(cnt_all ~ 
                       SST_39_anom  + #smaller but non-sig pval with anom
                       #SST_39 +
                       Sard + 
                       NPGO_lag1, 
          data = monthly_anom %>% filter(Cetacean.Common.Name == 'Dalls porpoise')))
pchisq(deviance(nb), df.residual(nb), lower.tail = F)
#w/o fish
nb <- summary(glm.nb(cnt_all ~ 
                       SST_39_anom + CBA_North, 
          data = monthly_anom %>% filter(Cetacean.Common.Name == 'Dalls porpoise')))
pchisq(deviance(nb), df.residual(nb), lower.tail = F)

#dolphinidae
mod_select <- regsubsets(cnt_all ~ 
           SST_39 + PDO_lag1 + SST_39_anom_lag1 +
          PDO_lag2 + SST_44_lag2 + SST_39_anom_lag2 + SST_44_anom_lag2,
          data = monthly_anom %>% filter(type == 'Dolphinidae'), nbest = 4, really.big = T)
summary(mod_select)

nb <- summary(glm.nb(cnt_all ~ 
                       #SST_39 + 
                       #SST_39_anom_lag1 +
                       SST_39_lag2 +
                       #SST_39_anom_lag2 + #both sst and sst_anom work okay
                       PDO_lag1, 
          data = monthly_anom %>% filter(type == 'Dolphinidae')))
#try poisson for underdispersed rel to nb
pois <- summary(glm(cnt_all ~ PDO_lag1 + SST_39_anom_lag2, 
          data = monthly_anom %>% filter(type == 'Dolphinidae'), family = 'poisson'))
pchisq(deviance(nb), df.residual(nb), lower.tail = F)
pchisq(deviance(pois), df.residual(pois), lower.tail = F)

z <- glm(cnt_all ~ PDO_lag1 + SST_39_anom_lag2, 
          data = monthly_anom %>% filter(type == 'Dolphinidae'), family = 'poisson')
anova(z, test = "Chisq")

summary(lm(cnt_all ~ PDO_lag1 + SST_39_anom_lag2, 
          data = monthly_anom %>% filter(type == 'Dolphinidae')))

#####Striped
mod_select <- regsubsets(cnt_all ~ CBA_North + MEI_lag1 + PDO_lag1 + SST_44_lag2,
          data = monthly_anom %>% filter(Cetacean.Common.Name == 'Striped dolphin'), 
          nbest = 3, really.big = T)
summary(mod_select)

nb <- glm.nb(cnt_all ~ 
               CBA_North + 
               MEI_lag1 + 
               PDO_lag1 + 
               SST_44_lag2, 
          data = monthly_anom %>% filter(Cetacean.Common.Name == 'Striped dolphin'))
sum <- summary(nb)
plot(nb)
pois <- glm(cnt_all ~ 
              CBA_North + 
              #PDO_lag1 +
               MEI_lag1
               #SST_44_lag2 +
               , 
          data = monthly_anom %>% filter(Cetacean.Common.Name == 'Striped dolphin'), family = 'poisson')
sum <- summary(pois)
plot(pois)
pchisq(deviance(sum), df.residual(sum), lower.tail = F) # pvalue = 0.96

####Humpy - sample size too small, nothing significant
# mod_select <- regsubsets(cnt_all ~ MEI + CBA_North + CBA_South + 
#           MEI_lag1 + PDO_lag1 + CBA_South_lag1,
#           data = monthly_anom %>% filter(Cetacean.Common.Name == 'Humpback whale'), 
#           nbest = 3, really.big = T)
# summary(mod_select)
# 
# nb <- glm.nb(cnt_all ~ 
#                CBA_North + 
#                MEI_lag1 + 
#                PDO_lag1 + 
#                SST_44_lag2, 
#           data = monthly_anom %>% filter(Cetacean.Common.Name == 'Humpback whale'))
# sum <- summary(nb)
# plot(nb)
# pois <- glm(cnt_all ~ 
#               #MEI + 
#               #CBA_North + 
#               #CBA_South + 
#           #MEI_lag1 + 
#             PDO_lag1 + 
#             CBA_South_lag1, 
#           data = monthly_anom %>% filter(Cetacean.Common.Name == 'Humpback whale'), family = 'poisson')
# sum <- summary(pois)
# plot(pois)
# pchisq(deviance(sum), df.residual(sum), lower.tail = F) #

```

