
```{r, echo = F}
library(ggplot2)
library(boot)
library(tidyr)
#library(ggmap)
library(data.table)
#library(cowplot)
library(knitr)
library(reshape2)
library(stringr)
library(magrittr)
library(scales)
library(stats) 
library(corrplot)
library(Hmisc) # rcorr()
library(MARSS)
library(forecast)
library(datasets)
library(gridExtra)
library(reshape2)
library(tseries)
library(urca)
library(broom)
library(dplyr)
library(mice)
library(rstudioapi)
library(mgcv)
library(MuMIn)
library(gratia)
library(here)

source(here::here('PNW Strands Manuscript', 'mydraw.gam.R'))

# path <- getActiveDocumentContext()$path
# setwd(dirname(path))

source(here::here('PNW Strands Manuscript', 'PlotTheme.R'))

flattenCorrMatrix <- function(cormat, pmat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
    )
}

```

```{r data, echo = F, results = 'hide'}

#impute missing covariate data following this example 
#https://www.analyticsvidhya.com/blog/2016/03/tutorial-powerful-packages-imputing-missing-values/

#2000-2018; not available after 2018; variables already scaled in Satelite_vars_PNW.R
covs_local <- read.csv(here::here('PNW Strands Manuscript', 'copernicus_dat.csv'))
#covs_loc[is.na(covs_loc)] <- 0  

#2000-2019
chla <- read.csv(here::here('PNW Strands Manuscript', 'chl_data.csv')) %>%
  transform(month = month(date), year = year(date)) %>%
  dplyr::select(-date) %>% 
  transform(chl = scale(chl)) %>%
  filter(year < 2020)

#cetcovs00-19.csv created in OceanDataLoad.R in OceanData folder
covs_cet <- read.csv(here::here('PNW Strands Manuscript', 'CetCovs00_19.csv'), header = T, stringsAsFactors = F) 

#upwelling most corr with SST - use to impute sst45
covs_miss <- data.frame(SST45 = as.numeric(covs_cet$SST45), 
                        upwell_imp = as.numeric(covs_cet$upwell39))

imp_sst45 <- mice(covs_miss[,1:2], m=2, maxit = 50, method = 'pmm', seed = 500)

covs_cet <- complete(imp_sst45,2) %>%
  dplyr::select(-upwell_imp) %>%
  bind_cols(covs_cet %>% dplyr::select(-SST45))

#use sst45 to impute sst 39 (sst much fewer missing to begin with)
covs_miss <- data.frame(SST39 = as.numeric(covs_cet$SST39), 
                        SST45_imp = as.numeric(covs_cet$SST45))

imp_sst39 <- mice(covs_miss[,1:2], m=2, maxit = 50, method = 'pmm', seed = 500)

covs_cet <- complete(imp_sst39,2) %>%
  dplyr::select(-SST45_imp) %>%
  bind_cols(covs_cet %>% dplyr::select(-SST39)) 

covs_merge <- covs_cet %>% 
  dplyr::select(year, month, PDO, MEI, SST45, upwell39, NPGO) %>%
  merge(covs_local %>% dplyr::select(-temp), by = c('year', 'month'), all = T) %>%
  merge(chla, by = c('year', 'month'), all = T) 

covs_cet <- covs_merge %>%
  arrange(year, month) #%>%
  # transform(month = factor(month, levels = c(1:12)))

# covs[is.na(covs)] <- 0

covs_an <- covs_cet %>%
  group_by(year) %>%
  dplyr::summarize(MEI = mean(MEI, na.rm = T), PDO = mean(PDO, na.rm = T),
                   sst = mean(SST45, na.rm = T), upwell = mean(upwell39, na.rm = T),
                   NPGO = mean(NPGO, na.rm = T), chla = mean(chl, na.rm = T),
                   mld = mean(mld, na.rm = T),
                   uwnd = mean(uwnd, na.rm = T), vwnd = mean(vwnd, na.rm = T))

#note - the naming of these sst variables is a little confusing in this script, but:
#sst2 (from coperniculs ctd 'temp'), sst from ecosys assessment buoy, and 
# sst_sali (erroneously named sst2 in imputation for convenience) from sat data of salish sea
# corr(cbind(data.frame(covs_an$sst), data.frame(covs_an$sst2)))
# corr(cbind(data.frame(covs_an$sst), data.frame(covs_an$sst2)))
# corr(cbind(data.frame(covs_an$sst), data.frame(covs_an$sst2)))
# corr(cbind(data.frame(covs_an$sst), data.frame(covs_an$sst2)))
# corr(cbind(data.frame(covs_an$sst), data.frame(covs_an$sst2)))

# plot(covs_an$sst)
# lines(covs_an$sst)
# plot(covs_an$sst2)
# lines(covs_an$sst2)
# plot(covs_an$sst_sali)
# lines(covs_an$sst_sali)

#Monthly anomalies separate species
cet_mo <- read.csv(here::here('PNW Strands Manuscript', "monthly_anom_cet.csv"), 
                   header = TRUE, na.strings = "NA", stringsAsFactors = FALSE) %>%
  dplyr::rename(Sp = Cetacean.Common.Name, Year = Year.of.Observation) %>%
  filter(Sp %in% c('Gray whale', 
                    #'Pacific white-sided dolphin', 
                    'Humpback whale', 
                    'Harbor porpoise', 'Striped dolphin', 'Dalls porpoise'))  %>%
  transform(month = factor(Month.of.Observation,
                                      levels = c('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN',
                                                 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'))) %>%
  transform(month = as.numeric(month)) %>%
  dplyr::rename(year = Year, cnt = cnt_all) %>%
  dplyr::select(year, month, Sp, cnt) 

# fill <- data.frame(year = rep(c(2000:2018), each = 12),
#                    month = rep(c(1:12), times = length(c(2000:2018))),
#                    Sp = rep(c('Harbor porpoise'), times = length(c(2000:2018))*12))
                 
#Annual strandings separate species
cet_an <- cet_mo %>%
  group_by(year, Sp) %>%
  dplyr::summarize(cnt = sum(cnt))

cor_test <- rcorr(as.matrix(covs_merge[,-c(1:2)]))
cor_vals <- flattenCorrMatrix(cor_test$r, cor_test$P) %>% arrange(cor)
corrplot(cor_test$r, type = "lower", order = "original", p.mat = cor_test$P, 
         insig = "blank", sig.level = 0.01, tl.col = "black", tl.cex = .9, number.cex = .2)
#correlated > 0.65 upwell/mld, sst/mld*, uwnd/vwnd, upwell/vwnd**, mld/wind, ssh/PDO/MEI -- makes sense
cor_combos <- cor_vals %>% filter(cor > 0.31 | cor < -0.31)

# write.csv(covs_cet, 'covs_cet.csv', row.names = F)

#opened up cet_covs.csv and manually adjusted env variables to lag them
covs_all <- read.csv(here::here('PNW Strands Manuscript', 'covs_cet_lagged.csv'), 
                     header = T, stringsAsFactors = F) %>%
    transform(PDO_lag = mean(c(PDO_lag1, PDO_lag2, PDO_lag3), na.rm = T)) %>%
    transform(MEI_lag = mean(c(MEI_lag1, MEI_lag2, MEI_lag3), na.rm = T)) %>%
    transform(SST45_lag = mean(c(SST45_lag1, SST45_lag2, SST45_lag3), na.rm = T)) %>%
    transform(upwell39_lag = mean(c(upwell39_lag1, upwell39_lag2, upwell39_lag3), na.rm = T)) %>%
    transform(NPGO_lag = mean(c(NPGO_lag1, NPGO_lag2, NPGO_lag3), na.rm = T)) %>%
    transform(vwnd_lag = mean(c(vwnd_lag1, vwnd_lag2, vwnd_lag3), na.rm = T)) %>%
    transform(uwnd_lag = mean(c(uwnd_lag1, uwnd_lag2, uwnd_lag3), na.rm = T)) %>%
    transform(mld_lag = mean(c(mld_lag1, mld_lag2, mld_lag3), na.rm = T)) %>%
    transform(ssh_lag = mean(c(ssh_lag1, ssh_lag2, ssh_lag3), na.rm = T)) %>%
    transform(chl_lag = mean(c(chl_lag1, chl_lag2, chl_lag3), na.rm = T))

```


```{r hp original}

dat_hp <- cet_mo %>% filter(Sp == 'Harbor porpoise') %>%
  merge(covs_all, by = c('year', 'month'), all = T) %>%
  transform(cnt = ifelse(is.na(cnt), 0, cnt), Sp = ifelse(is.na(Sp), 'Harbor porpoise', Sp)) %>%
  # transform(month = factor(month)) %>%
  filter(!is.na(year)) 
dat_hp[is.na(dat_hp)] <- 0

mod0 <- gam(cnt ~ 1, family = 'poisson', method = 'REML', data = dat_hp)
#summary(mod0) #1.5 strandings per month in months when there are strandings

mod1 <- gam(cnt ~ s(month, bs = 'cc') + s(year), 
            family = 'poisson', method = 'REML', select = T, 
            data = dat_hp, drop.unused.levels = F)
summary(mod1)

mod_full <- gam(cnt ~ s(month, bs = 'cc') +
              # s(PDO_lag1) +
              # s(SST45) +
                s(mld_lag1) +
                # s(vwnd) +
                # s(uwnd) +
                # s(upwell39_lag3) +
                # s(chl_lag2) +
                s(chl) +
                s(year),
            family = 'poisson', method = 'REML', select = T, 
            data = dat_hp, drop.unused.levels = F)
summary(mod_full)
#mydraw.gam(mod_full)

dev.expl <- c(summary(mod1)$dev.expl,
              # summary(mod2)$dev.expl,
              # summary(mod3)$dev.expl,
              # summary(mod4)$dev.expl,
              # summary(mod5)$dev.expl,
              # summary(mod6)$dev.expl,
              # summary(mod_full)$dev.expl,
              summary(mod_full)$dev.expl)

AIC <- data.frame(AIC(mod0, mod1, mod_full)) %>%
  transform(delAIC = AIC-min(AIC(mod0, mod1, mod_full)[2])) %>%
  transform(delAIC = round(delAIC, 2), AIC = round(AIC, 2))

weights <- Weights(AIC$delAIC)

AIC$Weight <- round(weights, 2)
AIC$Dev.exp <- round(c(NA, dev.expl),2)

mod_best <- mod_full
summary(mod_best)

hp1 <- mydraw.gam(mod_best)[[1]] + ggtitle('') +
  xlab('Month') + ylab('Effect') +
    annotate('text', label = paste('edf','=','5.6,', 'p', '<', '0.01'), 
             x = 7, y = -2.3, size = 3, parse = F) +
  plot_theme(plot.title = element_text(size = 12)) + 
  scale_x_continuous(breaks = c(1,3,5,7,9,11), labels = c(1,3,5,7,9,11)) +
  scale_y_continuous(limits = c(-2.3, 2), breaks = seq(-2, 2, 1))
  
hp2 <- mydraw.gam(mod_best)[[4]] + ggtitle('') +
  xlab('') + ylab('') +
  plot_theme(plot.title = element_text(size = 12),
             axis.title.x = element_blank(),
             axis.title.y = element_blank()) +
  annotate('text', label = paste('edf','=','5.1,', 'p', '<', '0.01'),
                        x = 2011, y = -2.3, size = 3, parse = F) +
  scale_y_continuous(limits = c(-2.3, 2), breaks = seq(-2, 2, 1))
  
hp4 <- mydraw.gam(mod_best)[[2]] + ggtitle('') + 
  xlab('Mixed layer depth (lag)') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) + 
annotate('text', label = paste('edf','=','5.8,', 'p', '<', '0.01'), 
                        x = 0.7, y = -2.3, size = 3, parse = F) +
  scale_y_continuous(limits = c(-2.3, 2), breaks = seq(-2, 2, 1))
  
hp3 <- mydraw.gam(mod_best)[[3]] + ggtitle('') + 
  xlab('Chlorophyll') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) + 
  annotate('text', label = paste('edf','=','4.7,', 'p', '<', '0.01'), 
                        x = 0.8, y = -2.3, size = 3, parse = F) +
  scale_y_continuous(limits = c(-2.3, 2), breaks = seq(-2, 2, 1))

# hp2 <- mydraw.gam(mod_best)[[4]] + ggtitle('') + 
#   xlab('PDO (lag)') + ylab('') + 
#   plot_theme(plot.title = element_text(size = 12),
#              axis.title.y = element_blank()) + 
#   annotate('text', label = paste('edf','=','1.1,', 'p', '<', '0.05'), 
#                         x = 0.8, y = -2.3, size = 3, parse = F) +
#   scale_y_continuous(limits = c(-2.3, 2), breaks = seq(-2, 2, 1))

plot_grid(hp1, hp2, hp3, hp4, nrow = 1)
  
```


```{r hp inland}

cet_mo_inland <- read.csv(here::here("PNW Strands Manuscript", "monthly_anom_cet_inland.csv"), header = TRUE, na.strings = "NA", stringsAsFactors = FALSE) %>%
  dplyr::rename(Sp = Cetacean.Common.Name, Year = Year.of.Observation) %>%
  filter(Sp %in% c('Harbor porpoise'))  %>%
  transform(month = factor(Month.of.Observation,
                                      levels = c('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN',
                                                 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'))) %>%
  transform(month = as.numeric(month)) %>%
  dplyr::rename(year = Year, cnt = cnt_all) %>%
  dplyr::select(year, month, Sp, cnt) 

dat_hp <- cet_mo_inland %>% #filter(Sp == 'Harbor porpoise') %>%
  merge(covs_all, by = c('year', 'month'), all = T) %>%
  transform(cnt = ifelse(is.na(cnt), 0, cnt), Sp = ifelse(is.na(Sp), 'Harbor porpoise', Sp)) %>%
  # transform(month = factor(month)) %>%
  filter(!is.na(year)) 
dat_hp[is.na(dat_hp)] <- 0

mod0 <- gam(cnt ~ 1, family = 'poisson', method = 'REML', data = dat_hp)
#summary(mod0) #1.5 strandings per month in months when there are strandings

mod1 <- gam(cnt ~ s(month, bs = 'cc') + s(year), 
            family = 'poisson', method = 'REML', select = T, 
            data = dat_hp, drop.unused.levels = F)
summary(mod1)

mod_full <- gam(cnt ~ s(month, bs = 'cc') +
              # s(PDO_lag1) +
              # s(SST45_lag2) +
                s(mld) +
                # s(vwnd) +
                # s(uwnd) +
                # s(upwell39_lag3) +
                # s(chl_lag2) + #curved relationship here
                s(chl) + #more linear relationship here
                s(year),
            family = 'poisson', method = 'REML', select = T, 
            data = dat_hp, drop.unused.levels = F)
summary(mod_full)
#mydraw.gam(mod_full)

dev.expl <- c(summary(mod1)$dev.expl,
              # summary(mod2)$dev.expl,
              # summary(mod3)$dev.expl,
              # summary(mod4)$dev.expl,
              # summary(mod5)$dev.expl,
              # summary(mod6)$dev.expl,
              # summary(mod_full)$dev.expl,
              summary(mod_full)$dev.expl)

AIC <- data.frame(AIC(mod0, mod1, mod_full)) %>%
  transform(delAIC = AIC-min(AIC(mod0, mod1, mod_full)[2])) %>%
  transform(delAIC = round(delAIC, 2), AIC = round(AIC, 2))

weights <- Weights(AIC$delAIC)

AIC$Weight <- round(weights, 2)
AIC$Dev.exp <- round(c(NA, dev.expl),2)

mod_best <- mod_full
summary(mod_best)

hp1 <- mydraw.gam(mod_best)[[1]] + ggtitle('') +
  xlab('Month') + ylab('Effect') +
    annotate('text', label = paste('edf','=','5.6,', 'p', '<', '0.01'), 
             x = 7, y = -2.3, size = 3, parse = F) +
  plot_theme(plot.title = element_text(size = 12)) + 
  scale_x_continuous(breaks = c(1,3,5,7,9,11), labels = c(1,3,5,7,9,11)) +
  scale_y_continuous(limits = c(-2.3, 2), breaks = seq(-2, 2, 1))
  
hp2 <- mydraw.gam(mod_best)[[5]] + ggtitle('') + 
  xlab('') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.x = element_blank(),
             axis.title.y = element_blank()) + 
  annotate('text', label = paste('edf','=','5.1,', 'p', '<', '0.01'), 
                        x = 2011, y = -2.3, size = 3, parse = F) +
  scale_y_continuous(limits = c(-2.3, 2), breaks = seq(-2, 2, 1))
  
hp3 <- mydraw.gam(mod_best)[[3]] + ggtitle('') + 
  xlab('Mixed layer depth (lag)') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) + 
annotate('text', label = paste('edf','=','5.8,', 'p', '<', '0.01'), 
                        x = 0.7, y = -2.3, size = 3, parse = F) +
  scale_y_continuous(limits = c(-2.3, 2), breaks = seq(-2, 2, 1))
  
hp4 <- mydraw.gam(mod_best)[[4]] + ggtitle('') + 
  xlab('Chlorophyll') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) + 
  annotate('text', label = paste('edf','=','4.7,', 'p', '<', '0.01'), 
                        x = 0.8, y = -2.3, size = 3, parse = F) +
  scale_y_continuous(limits = c(-2.3, 2), breaks = seq(-2, 2, 1))

hp5 <- mydraw.gam(mod_best)[[2]] + ggtitle('') + 
  xlab('PDO (lag)') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) + 
  annotate('text', label = paste('edf','=','1.1,', 'p', '<', '0.05'), 
                        x = 0.8, y = -2.3, size = 3, parse = F) +
  scale_y_continuous(limits = c(-2.3, 2), breaks = seq(-2, 2, 1))

plot_grid(hp1, hp2, hp3, hp4, hp5, nrow = 1)
  
```


```{r hp OC}

cet_mo_OC <- read.csv(here::here('PNW Strands Manuscript', "monthly_anom_cet_OC.csv"), header = TRUE, na.strings = "NA", stringsAsFactors = FALSE) %>%
  dplyr::rename(Sp = Cetacean.Common.Name, Year = Year.of.Observation) %>%
  filter(Sp %in% c('Harbor porpoise'))  %>%
  transform(month = factor(Month.of.Observation,
                                      levels = c('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN',
                                                 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'))) %>%
  transform(month = as.numeric(month)) %>%
  dplyr::rename(year = Year, cnt = cnt_all) %>%
  dplyr::select(year, month, Sp, cnt) 

dat_hp <- cet_mo_OC %>% #filter(Sp == 'Harbor porpoise') %>%
  merge(covs_all, by = c('year', 'month'), all = T) %>%
  transform(cnt = ifelse(is.na(cnt), 0, cnt), Sp = ifelse(is.na(Sp), 'Harbor porpoise', Sp)) %>%
  # transform(month = factor(month)) %>%
  filter(!is.na(year)) 
dat_hp[is.na(dat_hp)] <- 0

mod0 <- gam(cnt ~ 1, family = 'poisson', method = 'REML', data = dat_hp)
#summary(mod0) #1.5 strandings per month in months when there are strandings

mod1 <- gam(cnt ~ s(month, bs = 'cc') + s(year), 
            family = 'poisson', method = 'REML', select = T, 
            data = dat_hp, drop.unused.levels = F)
summary(mod1)

mod_full <- gam(cnt ~ s(month, bs = 'cc') +
              # s(PDO_lag1) +
                # s(MEI) +
              # s(SST45) +
                s(mld_lag1) +
                # s(vwnd) +
                # s(uwnd) +
                # s(upwell39) +
                s(chl) +
                # s(chl) +
                s(year),
            family = 'poisson', method = 'REML', select = T, 
            data = dat_hp, drop.unused.levels = F)
summary(mod_full)
#mydraw.gam(mod_full)

dev.expl <- c(summary(mod1)$dev.expl,
              # summary(mod2)$dev.expl,
              # summary(mod3)$dev.expl,
              # summary(mod4)$dev.expl,
              # summary(mod5)$dev.expl,
              # summary(mod6)$dev.expl,
              # summary(mod_full)$dev.expl,
              summary(mod_full)$dev.expl)

AIC <- data.frame(AIC(mod0, mod1, mod_full)) %>%
  transform(delAIC = AIC-min(AIC(mod0, mod1, mod_full)[2])) %>%
  transform(delAIC = round(delAIC, 2), AIC = round(AIC, 2))

weights <- Weights(AIC$delAIC)

AIC$Weight <- round(weights, 2)
AIC$Dev.exp <- round(c(NA, dev.expl),2)

mod_best <- mod_full
summary(mod_best)

hp1 <- mydraw.gam(mod_best)[[1]] + ggtitle('') +
  xlab('Month') + ylab('Effect') +
    annotate('text', label = paste('edf','=','5.6,', 'p', '<', '0.01'), 
             x = 7, y = -2.3, size = 3, parse = F) +
  plot_theme(plot.title = element_text(size = 12)) + 
  scale_x_continuous(breaks = c(1,3,5,7,9,11), labels = c(1,3,5,7,9,11)) +
  scale_y_continuous(limits = c(-2.3, 2), breaks = seq(-2, 2, 1))
  
hp2 <- mydraw.gam(mod_best)[[5]] + ggtitle('') + 
  xlab('') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.x = element_blank(),
             axis.title.y = element_blank()) + 
  annotate('text', label = paste('edf','=','5.1,', 'p', '<', '0.01'), 
                        x = 2011, y = -2.3, size = 3, parse = F) +
  scale_y_continuous(limits = c(-2.3, 2), breaks = seq(-2, 2, 1))
  
hp3 <- mydraw.gam(mod_best)[[3]] + ggtitle('') + 
  xlab('Mixed layer depth (lag)') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) + 
annotate('text', label = paste('edf','=','5.8,', 'p', '<', '0.01'), 
                        x = 0.7, y = -2.3, size = 3, parse = F) +
  scale_y_continuous(limits = c(-2.3, 2), breaks = seq(-2, 2, 1))
  
hp4 <- mydraw.gam(mod_best)[[4]] + ggtitle('') + 
  xlab('Chlorophyll') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) + 
  annotate('text', label = paste('edf','=','4.7,', 'p', '<', '0.01'), 
                        x = 0.8, y = -2.3, size = 3, parse = F) +
  scale_y_continuous(limits = c(-2.3, 2), breaks = seq(-2, 2, 1))

hp5 <- mydraw.gam(mod_best)[[2]] + ggtitle('') + 
  xlab('PDO (lag)') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) + 
  annotate('text', label = paste('edf','=','1.1,', 'p', '<', '0.05'), 
                        x = 0.8, y = -2.3, size = 3, parse = F) +
  scale_y_continuous(limits = c(-2.3, 2), breaks = seq(-2, 2, 1))

plot_grid(hp1, hp2, hp3, hp4, hp5, nrow = 1)
  
```

```{r grey monthly}

dat_gw <- cet_mo %>% filter(Sp == 'Gray whale') %>%
  merge(covs_all, by = c('year', 'month'), all = T) %>%
  transform(cnt = ifelse(is.na(cnt), 0, cnt), Sp = ifelse(is.na(Sp), 'Gray whale', Sp)) %>%
  filter(!is.na(year))
# gw_yr <- dat_gw %>% group_by(year) %>% summarize(cnt = sum(cnt))
# ggplot(gw_yr, aes(x = year, y = cnt)) + geom_line() + geom_point()

mod0 <- gam(cnt ~ 1, family = 'poisson', method = 'REML', data = dat_gw)
#summary(mod0) #0.7 strandings per month in months when there are strandings

mod1 <- gam(cnt ~ s(month, bs = 'cc') + s(year), 
            family = 'poisson', method = 'REML', select = T, 
            data = dat_gw, drop.unused.levels = F)
summary(mod1)

mod_full <- gam(cnt ~ s(month, bs = 'cc') +  +
              s(PDO_lag1) +
              # s(MEI) +
              s(SST45) +
                # s(mld_lag2) +
                # s(vwnd) +
                # s(uwnd) +
                 s(chl) +
                # s(upwell39) +
                    s(year), 
            family = 'poisson', method = 'REML',select = T, 
             data = dat_gw, drop.unused.levels = F)
summary(mod_full)

dev.expl <- c(summary(mod1)$dev.expl,
              summary(mod_full)$dev.expl)

AIC <- data.frame(AIC(mod0, mod1, mod_full)) %>%
  transform(delAIC = AIC-min(AIC(mod0, mod1, mod_full)[2])) %>%
  transform(delAIC = round(delAIC, 2), AIC = round(AIC, 2))

weights <- Weights(AIC$delAIC)

AIC$Weight <- round(weights, 2)
AIC$Dev.exp <- round(c(NA, dev.expl),2)

mod_best <- mod_full
summary(mod_full)
gam.check(mod_best)

#mydraw.gam(mod_best)

gw1 <- mydraw.gam(mod_best)[[1]] + ggtitle('') +
  xlab('Month') + ylab('Effect') +
    annotate('text', label = paste('edf','=','5.4,', 'p', '<', '0.01'), 
             x = 7, y = -2.5, size = 3.3, parse = F) +
  plot_theme(plot.title = element_text(size = 12)) + 
  scale_x_continuous(breaks = c(1,3,5,7,9,11), labels = c(1,3,5,7,9,11)) +
  scale_y_continuous(limits = c(-2.5, 2), breaks = c(-3:2))

gw2 <- mydraw.gam(mod_best)[[5]] + ggtitle('') + 
  xlab('') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.x = element_blank(),
             axis.title.y = element_blank()) + 
  annotate('text', label = paste('edf','=','5.9,', 'p', '<', '0.01'), 
                        x = 2012, y = -2, size = 3.3, parse = F) +
  scale_y_continuous(limits = c(-2, 2), breaks = c(-3:2))
  
gw3 <- mydraw.gam(mod_best)[[4]] + ggtitle('') + 
  xlab('Chlorophyll') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) +
  annotate('text', label = paste('edf','=','3.3,', 'p', '<', '0.05'), 
                        x = 1, y = -2, size = 3.3, parse = F) +
  scale_x_continuous(limits = c(-1,3)) +
  scale_y_continuous(limits = c(-2, 2), breaks = c(-2:2))
  
gw4 <- mydraw.gam(mod_best)[[3]] + ggtitle('') +
  xlab('SST') + ylab('') +
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) +
  annotate('text', label = paste('edf','=','1.0,', 'p', '< ', '0.1'),
                        x = 0.5, y = -2, size = 3.3, parse = F) +
  scale_y_continuous(limits = c(-2, 2), breaks = c(-2:2))

gw5 <- mydraw.gam(mod_best)[[2]] + ggtitle('') +
  xlab('PDO (lag)') + ylab('') +
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) +
  annotate('text', label = paste('edf','=','2.2,', 'p', '<', '0.01'),
                        x = 0.3, y = -2, size = 3.3, parse = F) +
  scale_y_continuous(limits = c(-2, 2), breaks = c(-2:2))

plot_grid(gw1, gw2, gw4, gw3, gw5, nrow = 1)

```


```{r grey monthly ziP}

dat_gw <- cet_mo %>% filter(Sp == 'Gray whale') %>%
  merge(covs_all, by = c('year', 'month'), all = T) %>%
  transform(cnt = ifelse(is.na(cnt), 0, cnt), Sp = ifelse(is.na(Sp), 'Gray whale', Sp)) %>%
  filter(!is.na(year))
# gw_yr <- dat_gw %>% group_by(year) %>% summarize(cnt = sum(cnt))
# ggplot(gw_yr, aes(x = year, y = cnt)) + geom_line() + geom_point()

mod0z <- gam(cnt ~ 1, family = 'ziP', method = 'REML', data = dat_gw)
#summary(mod0) #0.7 strandings per month in months when there are strandings

mod1z <- gam(cnt ~ s(month, bs = 'cc') + s(year), 
            family = 'ziP', method = 'REML', select = T, 
            data = dat_gw, drop.unused.levels = F)
summary(mod1z)

mod_fullz <- gam(cnt ~ s(month, bs = 'cc') +  +
              s(PDO_lag1) +
              # s(MEI) +
              s(SST45) +
                # s(mld_lag2) +
                # s(vwnd) +
                # s(uwnd) +
                 s(chl) +
                # s(upwell39) +
                    s(year), 
            family = 'ziP', method = 'REML',select = T, 
             data = dat_gw, drop.unused.levels = F)
summary(mod_fullz)

dev.explz <- c(summary(mod1)$dev.expl,
              summary(mod_full)$dev.expl)

AIC <- data.frame(AIC(mod0, mod1, mod_full)) %>%
  transform(delAIC = AIC-min(AIC(mod0, mod1, mod_full)[2])) %>%
  transform(delAIC = round(delAIC, 2), AIC = round(AIC, 2))

weights <- Weights(AIC$delAIC)

AIC$Weight <- round(weights, 2)
AIC$Dev.exp <- round(c(NA, dev.expl),2)

mod_best <- mod_full
summary(mod_full)
gam.check(mod_best)

#mydraw.gam(mod_fullz)

gw1 <- mydraw.gam(mod_best)[[1]] + ggtitle('') +
  xlab('Month') + ylab('Effect') +
    annotate('text', label = paste('edf','=','5.4,', 'p', '<', '0.01'), 
             x = 7, y = -2.5, size = 3.3, parse = F) +
  plot_theme(plot.title = element_text(size = 12)) + 
  scale_x_continuous(breaks = c(1,3,5,7,9,11), labels = c(1,3,5,7,9,11)) +
  scale_y_continuous(limits = c(-2.5, 2), breaks = c(-3:2))

gw2 <- mydraw.gam(mod_best)[[5]] + ggtitle('') + 
  xlab('') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.x = element_blank(),
             axis.title.y = element_blank()) + 
  annotate('text', label = paste('edf','=','5.9,', 'p', '<', '0.01'), 
                        x = 2012, y = -2, size = 3.3, parse = F) +
  scale_y_continuous(limits = c(-2, 2), breaks = c(-3:2))
  
gw3 <- mydraw.gam(mod_best)[[4]] + ggtitle('') + 
  xlab('Chlorophyll') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) +
  annotate('text', label = paste('edf','=','3.3,', 'p', '<', '0.05'), 
                        x = 1, y = -2, size = 3.3, parse = F) +
  scale_x_continuous(limits = c(-1,3)) +
  scale_y_continuous(limits = c(-2, 2), breaks = c(-2:2))
  
gw4 <- mydraw.gam(mod_best)[[3]] + ggtitle('') +
  xlab('SST') + ylab('') +
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) +
  annotate('text', label = paste('edf','=','1.0,', 'p', '< ', '0.1'),
                        x = 0.5, y = -2, size = 3.3, parse = F) +
  scale_y_continuous(limits = c(-2, 2), breaks = c(-2:2))

gw5 <- mydraw.gam(mod_best)[[2]] + ggtitle('') +
  xlab('PDO (lag)') + ylab('') +
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) +
  annotate('text', label = paste('edf','=','2.2,', 'p', '<', '0.01'),
                        x = 0.3, y = -2, size = 3.3, parse = F) +
  scale_y_continuous(limits = c(-2, 2), breaks = c(-2:2))

plot_grid(gw1, gw2, gw4, gw3, gw5, nrow = 1)

```

```{r grey annual}

dat_gw_an <- cet_an %>% filter(Sp == 'Gray whale') %>%
  merge(covs_an, by = c('year'), all = T) %>%
  transform(cnt = ifelse(is.na(cnt), 0, cnt), Sp = ifelse(is.na(Sp), 'Gray whale', Sp)) %>%
  filter(year < 2019)

mod0 <- gam(cnt ~ 1, family = 'poisson', method = 'REML', data = dat_gw_an)
#summary(mod0) #0.7 strandings per month in months when there are strandings

mod1 <- gam(cnt ~ s(year), 
            family = 'poisson', method = 'REML', select = T, 
            data = dat_gw_an, drop.unused.levels = F)
summary(mod1)

mod_full <- gam(cnt ~ 
              # s(PDO) +
                # s(NPGO) +
              s(MEI) +
              # s(sst) +
                # s(mld) +
                # s(vwnd) +
                # s(uwnd) +
                 # s(chla), #+
                # s(upwell), #+
                    s(year),
            family = 'poisson', method = 'REML', select = T, 
             data = dat_gw_an, drop.unused.levels = F)
summary(mod_full)

# mod <- glm(cnt ~ upwell, family = 'poisson', data = dat_gw_an)
# summary(mod)

dev.expl <- c(summary(mod1)$dev.expl,
              summary(mod_full)$dev.expl)

AIC <- data.frame(AIC(mod0, mod1, mod_full)) %>%
  transform(delAIC = AIC-min(AIC(mod0, mod1, mod_full)[2])) %>%
  transform(delAIC = round(delAIC, 2), AIC = round(AIC, 2))

weights <- Weights(AIC$delAIC)

AIC$Weight <- round(weights, 2)
AIC$Dev.exp <- round(c(NA, dev.expl),2)

mod_best <- mod_full
summary(mod_full)
gam.check(mod_best)

#mydraw.gam(mod_best)

gw1 <- mydraw.gam(mod_best)[[1]] + ggtitle('') +
  xlab('Month') + ylab('Effect') +
    annotate('text', label = paste('edf','=','5.4,', 'p', '<', '0.01'), 
             x = 7, y = -2.5, size = 3.3, parse = F) +
  plot_theme(plot.title = element_text(size = 12)) + 
  scale_x_continuous(breaks = c(1,3,5,7,9,11), labels = c(1,3,5,7,9,11)) +
  scale_y_continuous(limits = c(-2.5, 2), breaks = c(-3:2))

gw2 <- mydraw.gam(mod_best)[[5]] + ggtitle('') + 
  xlab('') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.x = element_blank(),
             axis.title.y = element_blank()) + 
  annotate('text', label = paste('edf','=','5.9,', 'p', '<', '0.01'), 
                        x = 2012, y = -2, size = 3.3, parse = F) +
  scale_y_continuous(limits = c(-2, 2), breaks = c(-3:2))
  
gw3 <- mydraw.gam(mod_best)[[4]] + ggtitle('') + 
  xlab('Chlorophyll') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) +
  annotate('text', label = paste('edf','=','3.3,', 'p', '<', '0.05'), 
                        x = 1, y = -2, size = 3.3, parse = F) +
  scale_x_continuous(limits = c(-1,3)) +
  scale_y_continuous(limits = c(-2, 2), breaks = c(-2:2))
  
gw4 <- mydraw.gam(mod_best)[[3]] + ggtitle('') +
  xlab('SST') + ylab('') +
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) +
  annotate('text', label = paste('edf','=','1.0,', 'p', '< ', '0.1'),
                        x = 0.5, y = -2, size = 3.3, parse = F) +
  scale_y_continuous(limits = c(-2, 2), breaks = c(-2:2))

gw5 <- mydraw.gam(mod_best)[[2]] + ggtitle('') +
  xlab('PDO (lag)') + ylab('') +
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) +
  annotate('text', label = paste('edf','=','2.2,', 'p', '<', '0.01'),
                        x = 0.3, y = -2, size = 3.3, parse = F) +
  scale_y_continuous(limits = c(-2, 2), breaks = c(-2:2))

plot_grid(gw1, gw2, gw4, gw3, gw5, nrow = 1)

```


```{r striped}

dat_str <- cet_mo %>% filter(Sp == 'Striped dolphin') %>%
  merge(covs_all, by = c('year', 'month'), all = T) %>%
  transform(cnt = ifelse(is.na(cnt), 0, cnt), Sp = ifelse(is.na(Sp), 'Striped dolphin', Sp)) %>%
  filter(!is.na(year))

mod0 <- gam(cnt ~ 1, family = 'poisson', method = 'REML', data = dat_str)
#summary(mod0) 
mod1 <- gam(cnt ~ s(month, bs = 'cc') + s(year), 
            family = 'poisson', method = 'REML', select = T,
            data = dat_str, drop.unused.levels = F)
summary(mod1)

mod_full <- gam(cnt ~ s(month, bs = 'cc') + 
                # s(PDO) +
                # s(MEI) +
                s(SST45_lag2) +
                # s(mld) +
                # s(vwnd) +
                # s(uwnd) +
                s(ssh) +
                # s(upwell39) +
              s(chl) +
              s(year),
            family = 'poisson', method = 'REML', select = T,
            data = dat_str, drop.unused.levels = F)
summary(mod_full)

dev.expl <- c(summary(mod1)$dev.expl,
              summary(mod_full)$dev.expl)

AIC <- data.frame(AIC(mod0, mod1, mod_full)) %>%
  transform(delAIC = AIC-min(AIC(mod0, mod1, mod_full)[2])) %>%
  transform(delAIC = round(delAIC, 2), AIC = round(AIC, 2))

weights <- Weights(AIC$delAIC)

AIC$Weight <- round(weights, 2)
AIC$Dev.exp <- round(c(NA, dev.expl),2)

mod_best <- mod_full
gam.check(mod_best)
summary(mod_best)

#mydraw.gam(mod_best)

str1 <- mydraw.gam(mod_best)[[1]] + ggtitle('') +
  xlab('Month') + ylab('Effect') +
    annotate('text', label = paste('edf','=','3.2,', 'p', '<', '0.01'), 
             x = 8, y = -3, size = 3.3, parse = F) +
  plot_theme(plot.title = element_text(size = 12)) + 
  scale_x_continuous(breaks = c(1,3,5,7,9,11), labels = c(1,3,5,7,9,11)) +
  scale_y_continuous(limits = c(-3, 2), breaks = c(-3:2))


str2 <- mydraw.gam(mod_best)[[5]] + ggtitle('') + 
  xlab('') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank(), 
             axis.title.x = element_blank()) + 
  annotate('text', label = paste('edf','=','1.1,', 'p', '<', '0.01'), 
                        x = 2011, y = -3, size = 3.3, parse = F) +
  scale_y_continuous(limits = c(-3, 2), breaks = seq(-3,3, 1))
  
str3 <- mydraw.gam(mod_best)[[3]] + ggtitle('') +
  xlab('Sea surface height') + ylab('') +
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) +
  annotate('text', label = paste('edf','=','3.9,', 'p', '<', '0.01'),
                        x = 0.8, y = -5.5, size = 3.3, parse = F) +
  scale_y_continuous(limits = c(-5.5, 2.2), breaks = c(-5:2)) +
  scale_x_continuous(limits = c(-1.4,2))
  
str4 <- mydraw.gam(mod_best)[[4]] + ggtitle('') + 
  xlab('Chlorophyll') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) + 
  annotate('text', label = paste('edf','=','1.7,', 'p', '<', '0.01'), 
                        x = 1.5, y = -3, size = 3.3, parse = F) +  
  scale_y_continuous(limits = c(-3, 2), breaks = seq(-3,2, 1)) #+
  # scale_x_continuous(limits = c(-3.5, 2))#

str5 <- mydraw.gam(mod_best)[[2]] + ggtitle('') + 
  xlab('SST (lag)') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) + 
  annotate('text', label = paste('edf','=','1.4,', 'p', '<', '0.1'), 
                        x = 0.5, y = -3, size = 3.3, parse = F) +  
  scale_y_continuous(limits = c(-3, 2), breaks = seq(-3,2, 1))
  
plot_grid(str1, str2, str5, str4, str3, nrow = 1)

```

```{r dalls}

dat_da <- cet_mo %>% filter(Sp == 'Dalls porpoise') %>%
  merge(covs_all, by = c('year', 'month'), all = T) %>%
  transform(cnt = ifelse(is.na(cnt), 0, cnt), Sp = ifelse(is.na(Sp), 'Dalls porpoise', Sp)) %>%
  filter(!is.na(year))

mod0 <- gam(cnt ~ 1, family = 'poisson', method = 'REML', data = dat_da)
#summary(mod0) 
mod1 <- gam(cnt ~ s(month, bs = 'cc') + s(year), 
            family = 'poisson', method = 'REML', select = T,
            data = dat_da, drop.unused.levels = F)
summary(mod1)

mod2 <- gam(cnt ~ s(month, bs = 'cc') + 
              # s(NPGO) +
              s(PDO_lag3) +
                s(SST45) +
                # s(mld_lag3) +
                # s(uwnd) +
              
                # s(chl) +
                # s(upwell39_lag3) +
              s(year),
            family = 'poisson', method = 'REML', data = dat_da, drop.unused.levels = F)
summary(mod2)

dev.expl <- c(summary(mod1)$dev.expl,
              summary(mod2)$dev.expl)

AIC <- data.frame(AIC(mod0, mod1, mod2)) %>%
  transform(delAIC = AIC-min(AIC(mod0, mod1, mod2)[2])) %>%
  transform(delAIC = round(delAIC, 2), AIC = round(AIC, 2))

weights <- Weights(AIC$delAIC)

AIC$Weight <- round(weights, 2)
AIC$Dev.exp <- round(c(NA, dev.expl),2)

mod_best <- mod2
summary(mod_best)

#mydraw.gam(mod_best)

da1 <- mydraw.gam(mod_best)[[1]] + ggtitle('') + 
  xlab('Month') + ylab('Effect')  + 
  plot_theme(plot.title = element_text(size = 12)) +
    annotate('text', label = paste('edf','=','1.5,', 'p', '<', '0.05'), 
             x = 7, y = -1.5, size = 3, parse = F) +
  plot_theme(plot.title = element_text(size = 12)) + 
  scale_x_continuous(breaks = c(1,3,5,7,9,11), labels = c(1,3,5,7,9,11)) +
  scale_y_continuous(limits = c(-1.5, 1.5))#, breaks = c(-1.5, 1.5))
  
da2 <- mydraw.gam(mod_best)[[4]] + ggtitle('') + 
  xlab('') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.x = element_blank(),
             axis.title.y = element_blank()) + 
  annotate('text', label = paste('edf','=','1.0,', 'p', '<', '0.01'), 
                        x = 2012, y = -1.5, size = 3, parse = F) +
  scale_y_continuous(limits = c(-1.5, 1.5))#, breaks = c(-1.5, 1.5))
  
da3 <- mydraw.gam(mod_best)[[2]] + ggtitle('') + 
  xlab('PDO (lag)') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) + 
  annotate('text', label = paste('edf','=','3.7,', 'p', '<', '0.05'), 
                        x = 1, y = -1.5, size = 3, parse = F) +
  scale_y_continuous(limits = c(-1.5, 2))#, breaks = c(-1.5, 1.5))
  
da4 <- mydraw.gam(mod_best)[[3]] + ggtitle('') + 
  xlab('SST') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) + 
  annotate('text', label = paste('edf','=','1.0,', 'p', '<', '0.1'), 
                        x = 1, y = -1.5, size = 3, parse = F) +
  scale_y_continuous(limits = c(-1.5, 1.5))#, breaks = c(-1.5, 1.5))
  
# da5 <- mydraw.gam(mod_best)[[5]] + ggtitle('') + 
#   xlab('Sea surface height') + ylab('') + 
#   plot_theme(plot.title = element_text(size = 12),
#              axis.title.y = element_blank()) + 
#   annotate('text', label = paste('edf','=','1.4,', 'p', '<', '0.01'), 
#                         x = 0.1, y = -1.5, size = 3, parse = F) +
#   scale_y_continuous(limits = c(-1.5, 1.5))#, breaks = c(-1.5, 1.5))
  
plot_grid(da1, da2, da4, da3, nrow = 1)


```


```{r humpies}

dat_hump <- cet_mo %>% filter(Sp == 'Humpback whale') %>%
  merge(covs_all, by = c('year', 'month'), all = T) %>%
  transform(cnt = ifelse(is.na(cnt), 0, cnt), Sp = ifelse(is.na(Sp), 'Humpback whale', Sp)) %>%
  filter(!is.na(year))

mod0 <- gam(cnt ~ 1, family = 'poisson', method = 'REML', data = dat_hump)
#summary(mod0) #1.7 strandings per month in months when there are strandings

mod1 <- gam(cnt ~ s(month, bs = 'cc') + s(year), 
            family = 'poisson', method = 'REML', select = T, 
            data = dat_hump, drop.unused.levels = F)
summary(mod1)

mod2 <- gam(cnt ~ s(month, bs = 'cc') + 
              # s(NPGO_lag3) +
              # s(PDO) +
              # s(MEI) +
                s(SST45_lag1) +
                # s(mld) +
                # s(uwnd) +
                s(chl_lag3) +
                # s(upwell39) +
              # s(ssh) +
              # s(vwnd_lag3)
            s(year),
            family = 'poisson', method = 'REML', select = T, 
            data = dat_hump, drop.unused.levels = F)
summary(mod2)

dev.expl <- c(summary(mod1)$dev.expl,
              summary(mod2)$dev.expl)

AIC <- data.frame(AIC(mod0, mod1, mod2)) %>%
  transform(delAIC = AIC-min(AIC(mod0, mod1, mod2)[2])) %>%
  transform(delAIC = round(delAIC, 2), AIC = round(AIC, 2))

weights <- Weights(AIC$delAIC)

AIC$Weight <- round(weights, 2)
AIC$Dev.exp <- round(c(NA, dev.expl),2)

mod_best <- mod2
summary(mod_best)

#mydraw.gam(mod2)

hump1 <- mydraw.gam(mod_best)[[1]] + ggtitle('') +
  xlab('Month') + ylab('Effect') +
    annotate('text', label = paste('edf','=','1.7,', 'p', '<', '0.05'), 
             x = 8, y = -1.5, size = 3, parse = F) +
  plot_theme(plot.title = element_text(size = 12)) + 
  scale_x_continuous(breaks = c(1,3,5,7,9,11), labels = c(1,3,5,7,9,11)) +
  scale_y_continuous(limits = c(-1.5, 1.5))
  
hump2 <- mydraw.gam(mod_best)[[4]] + ggtitle('') + 
  xlab(' ') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.x = element_blank(),
             axis.title.y = element_blank()) + 
  annotate('text', label = paste('edf','=','1.2,', 'p', '<', '0.05'), 
                        x = 2012, y = -1.8, size = 3, parse = F) +
  scale_y_continuous(limits = c(-1.8, 1.5))
  
hump3 <- mydraw.gam(mod_best)[[2]] + ggtitle('') + 
  xlab('SST (lag)') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) + 
annotate('text', label = paste('edf','=','0.7,', 'p', '<', '0.05'), 
                        x = 0.8, y = -1.5, size = 3, parse = F) +
  scale_y_continuous(limits = c(-1.5,1.8))
  
hump4 <- mydraw.gam(mod_best)[[3]] + ggtitle('') + 
  xlab('Chlorophyll (lag)') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) + 
  annotate('text', label = paste('edf','=','1.9,', 'p', '<', '0.05'), 
                        x = 1, y = -2.8, size = 3, parse = F) +
  scale_y_continuous(limits = c(-2.8, 2))
  
plot_grid(hump1, hump2, hump3, hump4, nrow = 1)
  
```


```{r humpies annual}

dat_hump_an <- cet_an %>% filter(Sp == 'Humpback whale') %>%
  merge(covs_an, by = c('year'), all = T) %>%
  transform(cnt = ifelse(is.na(cnt), 0, cnt), Sp = ifelse(is.na(Sp), 'Humpback whale', Sp)) %>%
  filter(year < 2019)

mod0 <- gam(cnt ~ 1, family = 'poisson', method = 'REML', data = dat_hump_an)
#summary(mod0) #1.7 strandings per month in months when there are strandings

mod_full <- gam(cnt ~ 
              # s(NPGO_lag3) +
              # s(PDO) +
              # s(MEI) +
                s(sst) +
                # s(mld) +
                # s(uwnd) +
                s(chla), #+
                # s(upwell), #+
              # s(ssh) +
              # s(vwnd_lag3)
              # s(year),
            family = 'poisson', method = 'REML', select = T, 
            data = dat_hump_an, drop.unused.levels = F)
summary(mod_full)

dev.expl <- c(summary(mod1)$dev.expl,
              summary(mod2)$dev.expl)

AIC <- data.frame(AIC(mod0, mod1, mod2)) %>%
  transform(delAIC = AIC-min(AIC(mod0, mod1, mod2)[2])) %>%
  transform(delAIC = round(delAIC, 2), AIC = round(AIC, 2))

weights <- Weights(AIC$delAIC)

AIC$Weight <- round(weights, 2)
AIC$Dev.exp <- round(c(NA, dev.expl),2)

mod_best <- mod_full
summary(mod_best)

#mydraw.gam(mod2)

hump1 <- mydraw.gam(mod_best)[[1]] + ggtitle('') +
  xlab('Month') + ylab('Effect') +
    annotate('text', label = paste('edf','=','1.7,', 'p', '<', '0.05'), 
             x = 8, y = -1.5, size = 3, parse = F) +
  plot_theme(plot.title = element_text(size = 12)) + 
  scale_x_continuous(breaks = c(1,3,5,7,9,11), labels = c(1,3,5,7,9,11)) +
  scale_y_continuous(limits = c(-1.5, 1.5))
  
hump3 <- mydraw.gam(mod_best)[[2]] + ggtitle('') + 
  xlab('SST (lag)') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) + 
annotate('text', label = paste('edf','=','0.7,', 'p', '<', '0.05'), 
                        x = 0.8, y = -1.5, size = 3, parse = F) +
  scale_y_continuous(limits = c(-1.5,1.8))
  
hump4 <- mydraw.gam(mod_best)[[3]] + ggtitle('') + 
  xlab('Chlorophyll (lag)') + ylab('') + 
  plot_theme(plot.title = element_text(size = 12),
             axis.title.y = element_blank()) + 
  annotate('text', label = paste('edf','=','1.9,', 'p', '<', '0.05'), 
                        x = 1, y = -2.8, size = 3, parse = F) +
  scale_y_continuous(limits = c(-2.8, 2))
  
plot_grid(hump1, hump2, hump3, hump4, nrow = 1)
  
```
